//------------------------------------------------------------------------------
// <auto-generated>
//     Este código fue generado por una herramienta.
//     Versión de runtime:4.0.30319.42000
//
//     Los cambios en este archivo podrían causar un comportamiento incorrecto y se perderán si
//     se vuelve a generar el código.
// </auto-generated>
//------------------------------------------------------------------------------

// 
// Microsoft.VSDesigner generó automáticamente este código fuente, versión=4.0.30319.42000.
// 
#pragma warning disable 1591

namespace AmxSoapServicesActivities.ChangeCustomerEmailWsReference {
    using System;
    using System.Web.Services;
    using System.Diagnostics;
    using System.Web.Services.Protocols;
    using System.Xml.Serialization;
    using System.ComponentModel;
    
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.7.2556.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Web.Services.WebServiceBindingAttribute(Name="CustomerReadServiceSoap11", Namespace="http://ericsson.com/services/ws_CIL_7")]
    public partial class CustomerReadService : System.Web.Services.Protocols.SoapHttpClientProtocol {
        
        private System.Threading.SendOrPostCallback customerReadOperationCompleted;
        
        private bool useDefaultCredentialsSetExplicitly;
        
        /// <remarks/>
        public CustomerReadService() {
            this.Url = global::AmxSoapServicesActivities.Properties.Settings.Default.AmxSoapServicesActivities_ChangeCustomerEmailWsReference_CustomerReadService;
            if ((this.IsLocalFileSystemWebService(this.Url) == true)) {
                this.UseDefaultCredentials = true;
                this.useDefaultCredentialsSetExplicitly = false;
            }
            else {
                this.useDefaultCredentialsSetExplicitly = true;
            }
        }
        
        public new string Url {
            get {
                return base.Url;
            }
            set {
                if ((((this.IsLocalFileSystemWebService(base.Url) == true) 
                            && (this.useDefaultCredentialsSetExplicitly == false)) 
                            && (this.IsLocalFileSystemWebService(value) == false))) {
                    base.UseDefaultCredentials = false;
                }
                base.Url = value;
            }
        }
        
        public new bool UseDefaultCredentials {
            get {
                return base.UseDefaultCredentials;
            }
            set {
                base.UseDefaultCredentials = value;
                this.useDefaultCredentialsSetExplicitly = true;
            }
        }
        
        /// <remarks/>
        public event customerReadCompletedEventHandler customerReadCompleted;
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Bare)]
        [return: System.Xml.Serialization.XmlElementAttribute("customerReadResponse", Namespace="http://ericsson.com/services/ws_CIL_7/customerread")]
        public customerReadResponse customerRead([System.Xml.Serialization.XmlElementAttribute(Namespace="http://ericsson.com/services/ws_CIL_7/customerread")] customerReadRequest customerReadRequest) {
            object[] results = this.Invoke("customerRead", new object[] {
                        customerReadRequest});
            return ((customerReadResponse)(results[0]));
        }
        
        /// <remarks/>
        public void customerReadAsync(customerReadRequest customerReadRequest) {
            this.customerReadAsync(customerReadRequest, null);
        }
        
        /// <remarks/>
        public void customerReadAsync(customerReadRequest customerReadRequest, object userState) {
            if ((this.customerReadOperationCompleted == null)) {
                this.customerReadOperationCompleted = new System.Threading.SendOrPostCallback(this.OncustomerReadOperationCompleted);
            }
            this.InvokeAsync("customerRead", new object[] {
                        customerReadRequest}, this.customerReadOperationCompleted, userState);
        }
        
        private void OncustomerReadOperationCompleted(object arg) {
            if ((this.customerReadCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.customerReadCompleted(this, new customerReadCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        public new void CancelAsync(object userState) {
            base.CancelAsync(userState);
        }
        
        private bool IsLocalFileSystemWebService(string url) {
            if (((url == null) 
                        || (url == string.Empty))) {
                return false;
            }
            System.Uri wsUri = new System.Uri(url);
            if (((wsUri.Port >= 1024) 
                        && (string.Compare(wsUri.Host, "localHost", System.StringComparison.OrdinalIgnoreCase) == 0))) {
                return true;
            }
            return false;
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.7.2556.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://ericsson.com/services/ws_CIL_7/customerread")]
    public partial class customerReadRequest {
        
        private inputAttributes inputAttributesField;
        
        private sessionChangeRequest sessionChangeRequestField;
        
        /// <remarks/>
        public inputAttributes inputAttributes {
            get {
                return this.inputAttributesField;
            }
            set {
                this.inputAttributesField = value;
            }
        }
        
        /// <remarks/>
        public sessionChangeRequest sessionChangeRequest {
            get {
                return this.sessionChangeRequestField;
            }
            set {
                this.sessionChangeRequestField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.7.2556.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://ericsson.com/services/ws_CIL_7/customerread")]
    public partial class inputAttributes {
        
        private long csIdField;
        
        private bool csIdFieldSpecified;
        
        private string csIdPubField;
        
        private bool syncWithDbField;
        
        private bool syncWithDbFieldSpecified;
        
        /// <remarks/>
        public long csId {
            get {
                return this.csIdField;
            }
            set {
                this.csIdField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool csIdSpecified {
            get {
                return this.csIdFieldSpecified;
            }
            set {
                this.csIdFieldSpecified = value;
            }
        }
        
        /// <remarks/>
        public string csIdPub {
            get {
                return this.csIdPubField;
            }
            set {
                this.csIdPubField = value;
            }
        }
        
        /// <remarks/>
        public bool syncWithDb {
            get {
                return this.syncWithDbField;
            }
            set {
                this.syncWithDbField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool syncWithDbSpecified {
            get {
                return this.syncWithDbFieldSpecified;
            }
            set {
                this.syncWithDbFieldSpecified = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.7.2556.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://ericsson.com/services/ws_CIL_7/customerread")]
    public partial class partyRoleAssignmentsListpartResponse {
        
        private long partyRoleIdField;
        
        private bool partyRoleIdFieldSpecified;
        
        private string partyRoleShnameField;
        
        private string partyRoleNameField;
        
        private string partyRoleDescriptionField;
        
        /// <remarks/>
        public long partyRoleId {
            get {
                return this.partyRoleIdField;
            }
            set {
                this.partyRoleIdField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool partyRoleIdSpecified {
            get {
                return this.partyRoleIdFieldSpecified;
            }
            set {
                this.partyRoleIdFieldSpecified = value;
            }
        }
        
        /// <remarks/>
        public string partyRoleShname {
            get {
                return this.partyRoleShnameField;
            }
            set {
                this.partyRoleShnameField = value;
            }
        }
        
        /// <remarks/>
        public string partyRoleName {
            get {
                return this.partyRoleNameField;
            }
            set {
                this.partyRoleNameField = value;
            }
        }
        
        /// <remarks/>
        public string partyRoleDescription {
            get {
                return this.partyRoleDescriptionField;
            }
            set {
                this.partyRoleDescriptionField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.7.2556.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://ericsson.com/services/ws_CIL_7/customerread")]
    public partial class listOfAssignmentsListpartResponse {
        
        private long familyIdField;
        
        private bool familyIdFieldSpecified;
        
        private long completionStatusField;
        
        private bool completionStatusFieldSpecified;
        
        private System.DateTime validFromField;
        
        private bool validFromFieldSpecified;
        
        /// <remarks/>
        public long familyId {
            get {
                return this.familyIdField;
            }
            set {
                this.familyIdField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool familyIdSpecified {
            get {
                return this.familyIdFieldSpecified;
            }
            set {
                this.familyIdFieldSpecified = value;
            }
        }
        
        /// <remarks/>
        public long completionStatus {
            get {
                return this.completionStatusField;
            }
            set {
                this.completionStatusField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool completionStatusSpecified {
            get {
                return this.completionStatusFieldSpecified;
            }
            set {
                this.completionStatusFieldSpecified = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(DataType="date")]
        public System.DateTime validFrom {
            get {
                return this.validFromField;
            }
            set {
                this.validFromField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool validFromSpecified {
            get {
                return this.validFromFieldSpecified;
            }
            set {
                this.validFromFieldSpecified = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.7.2556.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://lhsgroup.com/lhsws/money")]
    public partial class money {
        
        private double amountField;
        
        private string currencyField;
        
        /// <remarks/>
        public double amount {
            get {
                return this.amountField;
            }
            set {
                this.amountField = value;
            }
        }
        
        /// <remarks/>
        public string currency {
            get {
                return this.currencyField;
            }
            set {
                this.currencyField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.7.2556.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://ericsson.com/services/ws_CIL_7/customerread")]
    public partial class customerReadResponse {
        
        private money tbAmountField;
        
        private string createdByUserField;
        
        private string tbModeField;
        
        private string tbPurposeField;
        
        private string sioActionTypeField;
        
        private money sioThresholdAmtField;
        
        private long maxCarryOverLenghtField;
        
        private bool maxCarryOverLenghtFieldSpecified;
        
        private string maxCarryOverPeriodTypeField;
        
        private bool isIndividualOverdiscDisabledField;
        
        private bool isIndividualOverdiscDisabledFieldSpecified;
        
        private long familyIdField;
        
        private bool familyIdFieldSpecified;
        
        private listOfAssignmentsListpartResponse[] listOfAssignmentsField;
        
        private long csIdField;
        
        private bool csIdFieldSpecified;
        
        private string csIdPubField;
        
        private string csCodeField;
        
        private string csStatusField;
        
        private System.DateTime csStatusDateField;
        
        private bool csStatusDateFieldSpecified;
        
        private System.DateTime csActivationDateField;
        
        private bool csActivationDateFieldSpecified;
        
        private long csIdHighField;
        
        private bool csIdHighFieldSpecified;
        
        private string csIdHighPubField;
        
        private string csLevelCodeField;
        
        private bool paymentRespField;
        
        private bool paymentRespFieldSpecified;
        
        private string prgCodeField;
        
        private long rpcodeField;
        
        private bool rpcodeFieldSpecified;
        
        private string rpcodePubField;
        
        private string tradeCodeField;
        
        private long areaCodeField;
        
        private bool areaCodeFieldSpecified;
        
        private long costIdField;
        
        private bool costIdFieldSpecified;
        
        private string costCodePubField;
        
        private string csPasswordField;
        
        private long rsCodeField;
        
        private bool rsCodeFieldSpecified;
        
        private long wpCodeField;
        
        private bool wpCodeFieldSpecified;
        
        private long srCodeField;
        
        private bool srCodeFieldSpecified;
        
        private string csRemark1Field;
        
        private string csRemark2Field;
        
        private bool csBillInformationField;
        
        private bool csBillInformationFieldSpecified;
        
        private long expectPayCurrencyIdField;
        
        private bool expectPayCurrencyIdFieldSpecified;
        
        private string expectPayCurrencyIdPubField;
        
        private long csConvratetypePaymentField;
        
        private bool csConvratetypePaymentFieldSpecified;
        
        private string csConvratetypePaymentPubField;
        
        private long refundCurrencyIdField;
        
        private bool refundCurrencyIdFieldSpecified;
        
        private string refundCurrencyIdPubField;
        
        private long csConvratetypeRefundField;
        
        private bool csConvratetypeRefundFieldSpecified;
        
        private string csConvratetypeRefundPubField;
        
        private bool csCrcheckAgreedField;
        
        private bool csCrcheckAgreedFieldSpecified;
        
        private long custcatCodeField;
        
        private bool custcatCodeFieldSpecified;
        
        private string custcatCodePubField;
        
        private long csJurisdictionIdField;
        
        private bool csJurisdictionIdFieldSpecified;
        
        private string csJurisdictionCodeField;
        
        private bool csIncorporatedIndField;
        
        private bool csIncorporatedIndFieldSpecified;
        
        private string csBillcycleField;
        
        private string csBillcycleDescField;
        
        private long csLimitTr1Field;
        
        private bool csLimitTr1FieldSpecified;
        
        private string csLimitTr1PubField;
        
        private long csLimitTr2Field;
        
        private bool csLimitTr2FieldSpecified;
        
        private string csLimitTr2PubField;
        
        private long csLimitTr3Field;
        
        private bool csLimitTr3FieldSpecified;
        
        private string csLimitTr3PubField;
        
        private money csClimitField;
        
        private bool csContrespField;
        
        private bool csContrespFieldSpecified;
        
        private System.DateTime csLastBcDateField;
        
        private bool csLastBcDateFieldSpecified;
        
        private money csDepositField;
        
        private string csCreditscoreField;
        
        private string csCscreditStatusField;
        
        private string csCscreditRemarkField;
        
        private System.DateTime csCscreditDateField;
        
        private bool csCscreditDateFieldSpecified;
        
        private bool csDunningField;
        
        private bool csDunningFieldSpecified;
        
        private string csDunningModeField;
        
        private bool csPrepaymentField;
        
        private bool csPrepaymentFieldSpecified;
        
        private string csCollectorField;
        
        private long csFcIdField;
        
        private bool csFcIdFieldSpecified;
        
        private string csFcIdPubField;
        
        private money csCscurbalanceField;
        
        private money csPrevbalanceField;
        
        private money csUnbilledAmountField;
        
        private string csPaybehaviourField;
        
        private string csNoBouncePayField;
        
        private long csDealeridField;
        
        private bool csDealeridFieldSpecified;
        
        private string csDealeridPubField;
        
        private bool csInitPrepaidContrOwnerField;
        
        private bool csInitPrepaidContrOwnerFieldSpecified;
        
        private System.DateTime csCreationDateField;
        
        private bool csCreationDateFieldSpecified;
        
        private System.DateTime csDeactivationDateField;
        
        private bool csDeactivationDateFieldSpecified;
        
        private System.DateTime csSuspensionDateField;
        
        private bool csSuspensionDateFieldSpecified;
        
        private System.DateTime csReactivationDateField;
        
        private bool csReactivationDateFieldSpecified;
        
        private string lastModificationUserField;
        
        private long paymentRespIdField;
        
        private bool paymentRespIdFieldSpecified;
        
        private string csPaymntRespCodeField;
        
        private partyRoleAssignmentsListpartResponse[] partyRoleAssignmentsField;
        
        private string partyTypeField;
        
        private bool collIndField;
        
        private bool collIndFieldSpecified;
        
        private bool markedForReratingField;
        
        private bool markedForReratingFieldSpecified;
        
        private string externalCustomerIdField;
        
        private string externalCustomerSetIdField;
        
        private long maxCsLevelField;
        
        private bool maxCsLevelFieldSpecified;
        
        private string creditScoreField;
        
        private string creditScoreProviderField;
        
        private string csCscreditUserField;
        
        private bool performCreditScoringField;
        
        private bool performCreditScoringFieldSpecified;
        
        private string cslvlnameField;
        
        private long adrNationalityField;
        
        private bool adrNationalityFieldSpecified;
        
        private string adrNationalityPubField;
        
        private bool adrEmployeeField;
        
        private bool adrEmployeeFieldSpecified;
        
        private string csTestbillrunField;
        
        private string roundingCarryLeftOverField;
        
        private bool allowIndividualBillcycleIndField;
        
        private bool allowIndividualBillcycleIndFieldSpecified;
        
        /// <remarks/>
        public money tbAmount {
            get {
                return this.tbAmountField;
            }
            set {
                this.tbAmountField = value;
            }
        }
        
        /// <remarks/>
        public string createdByUser {
            get {
                return this.createdByUserField;
            }
            set {
                this.createdByUserField = value;
            }
        }
        
        /// <remarks/>
        public string tbMode {
            get {
                return this.tbModeField;
            }
            set {
                this.tbModeField = value;
            }
        }
        
        /// <remarks/>
        public string tbPurpose {
            get {
                return this.tbPurposeField;
            }
            set {
                this.tbPurposeField = value;
            }
        }
        
        /// <remarks/>
        public string sioActionType {
            get {
                return this.sioActionTypeField;
            }
            set {
                this.sioActionTypeField = value;
            }
        }
        
        /// <remarks/>
        public money sioThresholdAmt {
            get {
                return this.sioThresholdAmtField;
            }
            set {
                this.sioThresholdAmtField = value;
            }
        }
        
        /// <remarks/>
        public long maxCarryOverLenght {
            get {
                return this.maxCarryOverLenghtField;
            }
            set {
                this.maxCarryOverLenghtField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool maxCarryOverLenghtSpecified {
            get {
                return this.maxCarryOverLenghtFieldSpecified;
            }
            set {
                this.maxCarryOverLenghtFieldSpecified = value;
            }
        }
        
        /// <remarks/>
        public string maxCarryOverPeriodType {
            get {
                return this.maxCarryOverPeriodTypeField;
            }
            set {
                this.maxCarryOverPeriodTypeField = value;
            }
        }
        
        /// <remarks/>
        public bool isIndividualOverdiscDisabled {
            get {
                return this.isIndividualOverdiscDisabledField;
            }
            set {
                this.isIndividualOverdiscDisabledField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool isIndividualOverdiscDisabledSpecified {
            get {
                return this.isIndividualOverdiscDisabledFieldSpecified;
            }
            set {
                this.isIndividualOverdiscDisabledFieldSpecified = value;
            }
        }
        
        /// <remarks/>
        public long familyId {
            get {
                return this.familyIdField;
            }
            set {
                this.familyIdField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool familyIdSpecified {
            get {
                return this.familyIdFieldSpecified;
            }
            set {
                this.familyIdFieldSpecified = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlArrayItemAttribute("item", IsNullable=false)]
        public listOfAssignmentsListpartResponse[] listOfAssignments {
            get {
                return this.listOfAssignmentsField;
            }
            set {
                this.listOfAssignmentsField = value;
            }
        }
        
        /// <remarks/>
        public long csId {
            get {
                return this.csIdField;
            }
            set {
                this.csIdField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool csIdSpecified {
            get {
                return this.csIdFieldSpecified;
            }
            set {
                this.csIdFieldSpecified = value;
            }
        }
        
        /// <remarks/>
        public string csIdPub {
            get {
                return this.csIdPubField;
            }
            set {
                this.csIdPubField = value;
            }
        }
        
        /// <remarks/>
        public string csCode {
            get {
                return this.csCodeField;
            }
            set {
                this.csCodeField = value;
            }
        }
        
        /// <remarks/>
        public string csStatus {
            get {
                return this.csStatusField;
            }
            set {
                this.csStatusField = value;
            }
        }
        
        /// <remarks/>
        public System.DateTime csStatusDate {
            get {
                return this.csStatusDateField;
            }
            set {
                this.csStatusDateField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool csStatusDateSpecified {
            get {
                return this.csStatusDateFieldSpecified;
            }
            set {
                this.csStatusDateFieldSpecified = value;
            }
        }
        
        /// <remarks/>
        public System.DateTime csActivationDate {
            get {
                return this.csActivationDateField;
            }
            set {
                this.csActivationDateField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool csActivationDateSpecified {
            get {
                return this.csActivationDateFieldSpecified;
            }
            set {
                this.csActivationDateFieldSpecified = value;
            }
        }
        
        /// <remarks/>
        public long csIdHigh {
            get {
                return this.csIdHighField;
            }
            set {
                this.csIdHighField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool csIdHighSpecified {
            get {
                return this.csIdHighFieldSpecified;
            }
            set {
                this.csIdHighFieldSpecified = value;
            }
        }
        
        /// <remarks/>
        public string csIdHighPub {
            get {
                return this.csIdHighPubField;
            }
            set {
                this.csIdHighPubField = value;
            }
        }
        
        /// <remarks/>
        public string csLevelCode {
            get {
                return this.csLevelCodeField;
            }
            set {
                this.csLevelCodeField = value;
            }
        }
        
        /// <remarks/>
        public bool paymentResp {
            get {
                return this.paymentRespField;
            }
            set {
                this.paymentRespField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool paymentRespSpecified {
            get {
                return this.paymentRespFieldSpecified;
            }
            set {
                this.paymentRespFieldSpecified = value;
            }
        }
        
        /// <remarks/>
        public string prgCode {
            get {
                return this.prgCodeField;
            }
            set {
                this.prgCodeField = value;
            }
        }
        
        /// <remarks/>
        public long rpcode {
            get {
                return this.rpcodeField;
            }
            set {
                this.rpcodeField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool rpcodeSpecified {
            get {
                return this.rpcodeFieldSpecified;
            }
            set {
                this.rpcodeFieldSpecified = value;
            }
        }
        
        /// <remarks/>
        public string rpcodePub {
            get {
                return this.rpcodePubField;
            }
            set {
                this.rpcodePubField = value;
            }
        }
        
        /// <remarks/>
        public string tradeCode {
            get {
                return this.tradeCodeField;
            }
            set {
                this.tradeCodeField = value;
            }
        }
        
        /// <remarks/>
        public long areaCode {
            get {
                return this.areaCodeField;
            }
            set {
                this.areaCodeField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool areaCodeSpecified {
            get {
                return this.areaCodeFieldSpecified;
            }
            set {
                this.areaCodeFieldSpecified = value;
            }
        }
        
        /// <remarks/>
        public long costId {
            get {
                return this.costIdField;
            }
            set {
                this.costIdField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool costIdSpecified {
            get {
                return this.costIdFieldSpecified;
            }
            set {
                this.costIdFieldSpecified = value;
            }
        }
        
        /// <remarks/>
        public string costCodePub {
            get {
                return this.costCodePubField;
            }
            set {
                this.costCodePubField = value;
            }
        }
        
        /// <remarks/>
        public string csPassword {
            get {
                return this.csPasswordField;
            }
            set {
                this.csPasswordField = value;
            }
        }
        
        /// <remarks/>
        public long rsCode {
            get {
                return this.rsCodeField;
            }
            set {
                this.rsCodeField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool rsCodeSpecified {
            get {
                return this.rsCodeFieldSpecified;
            }
            set {
                this.rsCodeFieldSpecified = value;
            }
        }
        
        /// <remarks/>
        public long wpCode {
            get {
                return this.wpCodeField;
            }
            set {
                this.wpCodeField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool wpCodeSpecified {
            get {
                return this.wpCodeFieldSpecified;
            }
            set {
                this.wpCodeFieldSpecified = value;
            }
        }
        
        /// <remarks/>
        public long srCode {
            get {
                return this.srCodeField;
            }
            set {
                this.srCodeField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool srCodeSpecified {
            get {
                return this.srCodeFieldSpecified;
            }
            set {
                this.srCodeFieldSpecified = value;
            }
        }
        
        /// <remarks/>
        public string csRemark1 {
            get {
                return this.csRemark1Field;
            }
            set {
                this.csRemark1Field = value;
            }
        }
        
        /// <remarks/>
        public string csRemark2 {
            get {
                return this.csRemark2Field;
            }
            set {
                this.csRemark2Field = value;
            }
        }
        
        /// <remarks/>
        public bool csBillInformation {
            get {
                return this.csBillInformationField;
            }
            set {
                this.csBillInformationField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool csBillInformationSpecified {
            get {
                return this.csBillInformationFieldSpecified;
            }
            set {
                this.csBillInformationFieldSpecified = value;
            }
        }
        
        /// <remarks/>
        public long expectPayCurrencyId {
            get {
                return this.expectPayCurrencyIdField;
            }
            set {
                this.expectPayCurrencyIdField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool expectPayCurrencyIdSpecified {
            get {
                return this.expectPayCurrencyIdFieldSpecified;
            }
            set {
                this.expectPayCurrencyIdFieldSpecified = value;
            }
        }
        
        /// <remarks/>
        public string expectPayCurrencyIdPub {
            get {
                return this.expectPayCurrencyIdPubField;
            }
            set {
                this.expectPayCurrencyIdPubField = value;
            }
        }
        
        /// <remarks/>
        public long csConvratetypePayment {
            get {
                return this.csConvratetypePaymentField;
            }
            set {
                this.csConvratetypePaymentField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool csConvratetypePaymentSpecified {
            get {
                return this.csConvratetypePaymentFieldSpecified;
            }
            set {
                this.csConvratetypePaymentFieldSpecified = value;
            }
        }
        
        /// <remarks/>
        public string csConvratetypePaymentPub {
            get {
                return this.csConvratetypePaymentPubField;
            }
            set {
                this.csConvratetypePaymentPubField = value;
            }
        }
        
        /// <remarks/>
        public long refundCurrencyId {
            get {
                return this.refundCurrencyIdField;
            }
            set {
                this.refundCurrencyIdField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool refundCurrencyIdSpecified {
            get {
                return this.refundCurrencyIdFieldSpecified;
            }
            set {
                this.refundCurrencyIdFieldSpecified = value;
            }
        }
        
        /// <remarks/>
        public string refundCurrencyIdPub {
            get {
                return this.refundCurrencyIdPubField;
            }
            set {
                this.refundCurrencyIdPubField = value;
            }
        }
        
        /// <remarks/>
        public long csConvratetypeRefund {
            get {
                return this.csConvratetypeRefundField;
            }
            set {
                this.csConvratetypeRefundField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool csConvratetypeRefundSpecified {
            get {
                return this.csConvratetypeRefundFieldSpecified;
            }
            set {
                this.csConvratetypeRefundFieldSpecified = value;
            }
        }
        
        /// <remarks/>
        public string csConvratetypeRefundPub {
            get {
                return this.csConvratetypeRefundPubField;
            }
            set {
                this.csConvratetypeRefundPubField = value;
            }
        }
        
        /// <remarks/>
        public bool csCrcheckAgreed {
            get {
                return this.csCrcheckAgreedField;
            }
            set {
                this.csCrcheckAgreedField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool csCrcheckAgreedSpecified {
            get {
                return this.csCrcheckAgreedFieldSpecified;
            }
            set {
                this.csCrcheckAgreedFieldSpecified = value;
            }
        }
        
        /// <remarks/>
        public long custcatCode {
            get {
                return this.custcatCodeField;
            }
            set {
                this.custcatCodeField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool custcatCodeSpecified {
            get {
                return this.custcatCodeFieldSpecified;
            }
            set {
                this.custcatCodeFieldSpecified = value;
            }
        }
        
        /// <remarks/>
        public string custcatCodePub {
            get {
                return this.custcatCodePubField;
            }
            set {
                this.custcatCodePubField = value;
            }
        }
        
        /// <remarks/>
        public long csJurisdictionId {
            get {
                return this.csJurisdictionIdField;
            }
            set {
                this.csJurisdictionIdField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool csJurisdictionIdSpecified {
            get {
                return this.csJurisdictionIdFieldSpecified;
            }
            set {
                this.csJurisdictionIdFieldSpecified = value;
            }
        }
        
        /// <remarks/>
        public string csJurisdictionCode {
            get {
                return this.csJurisdictionCodeField;
            }
            set {
                this.csJurisdictionCodeField = value;
            }
        }
        
        /// <remarks/>
        public bool csIncorporatedInd {
            get {
                return this.csIncorporatedIndField;
            }
            set {
                this.csIncorporatedIndField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool csIncorporatedIndSpecified {
            get {
                return this.csIncorporatedIndFieldSpecified;
            }
            set {
                this.csIncorporatedIndFieldSpecified = value;
            }
        }
        
        /// <remarks/>
        public string csBillcycle {
            get {
                return this.csBillcycleField;
            }
            set {
                this.csBillcycleField = value;
            }
        }
        
        /// <remarks/>
        public string csBillcycleDesc {
            get {
                return this.csBillcycleDescField;
            }
            set {
                this.csBillcycleDescField = value;
            }
        }
        
        /// <remarks/>
        public long csLimitTr1 {
            get {
                return this.csLimitTr1Field;
            }
            set {
                this.csLimitTr1Field = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool csLimitTr1Specified {
            get {
                return this.csLimitTr1FieldSpecified;
            }
            set {
                this.csLimitTr1FieldSpecified = value;
            }
        }
        
        /// <remarks/>
        public string csLimitTr1Pub {
            get {
                return this.csLimitTr1PubField;
            }
            set {
                this.csLimitTr1PubField = value;
            }
        }
        
        /// <remarks/>
        public long csLimitTr2 {
            get {
                return this.csLimitTr2Field;
            }
            set {
                this.csLimitTr2Field = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool csLimitTr2Specified {
            get {
                return this.csLimitTr2FieldSpecified;
            }
            set {
                this.csLimitTr2FieldSpecified = value;
            }
        }
        
        /// <remarks/>
        public string csLimitTr2Pub {
            get {
                return this.csLimitTr2PubField;
            }
            set {
                this.csLimitTr2PubField = value;
            }
        }
        
        /// <remarks/>
        public long csLimitTr3 {
            get {
                return this.csLimitTr3Field;
            }
            set {
                this.csLimitTr3Field = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool csLimitTr3Specified {
            get {
                return this.csLimitTr3FieldSpecified;
            }
            set {
                this.csLimitTr3FieldSpecified = value;
            }
        }
        
        /// <remarks/>
        public string csLimitTr3Pub {
            get {
                return this.csLimitTr3PubField;
            }
            set {
                this.csLimitTr3PubField = value;
            }
        }
        
        /// <remarks/>
        public money csClimit {
            get {
                return this.csClimitField;
            }
            set {
                this.csClimitField = value;
            }
        }
        
        /// <remarks/>
        public bool csContresp {
            get {
                return this.csContrespField;
            }
            set {
                this.csContrespField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool csContrespSpecified {
            get {
                return this.csContrespFieldSpecified;
            }
            set {
                this.csContrespFieldSpecified = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(DataType="date")]
        public System.DateTime csLastBcDate {
            get {
                return this.csLastBcDateField;
            }
            set {
                this.csLastBcDateField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool csLastBcDateSpecified {
            get {
                return this.csLastBcDateFieldSpecified;
            }
            set {
                this.csLastBcDateFieldSpecified = value;
            }
        }
        
        /// <remarks/>
        public money csDeposit {
            get {
                return this.csDepositField;
            }
            set {
                this.csDepositField = value;
            }
        }
        
        /// <remarks/>
        public string csCreditscore {
            get {
                return this.csCreditscoreField;
            }
            set {
                this.csCreditscoreField = value;
            }
        }
        
        /// <remarks/>
        public string csCscreditStatus {
            get {
                return this.csCscreditStatusField;
            }
            set {
                this.csCscreditStatusField = value;
            }
        }
        
        /// <remarks/>
        public string csCscreditRemark {
            get {
                return this.csCscreditRemarkField;
            }
            set {
                this.csCscreditRemarkField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(DataType="date")]
        public System.DateTime csCscreditDate {
            get {
                return this.csCscreditDateField;
            }
            set {
                this.csCscreditDateField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool csCscreditDateSpecified {
            get {
                return this.csCscreditDateFieldSpecified;
            }
            set {
                this.csCscreditDateFieldSpecified = value;
            }
        }
        
        /// <remarks/>
        public bool csDunning {
            get {
                return this.csDunningField;
            }
            set {
                this.csDunningField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool csDunningSpecified {
            get {
                return this.csDunningFieldSpecified;
            }
            set {
                this.csDunningFieldSpecified = value;
            }
        }
        
        /// <remarks/>
        public string csDunningMode {
            get {
                return this.csDunningModeField;
            }
            set {
                this.csDunningModeField = value;
            }
        }
        
        /// <remarks/>
        public bool csPrepayment {
            get {
                return this.csPrepaymentField;
            }
            set {
                this.csPrepaymentField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool csPrepaymentSpecified {
            get {
                return this.csPrepaymentFieldSpecified;
            }
            set {
                this.csPrepaymentFieldSpecified = value;
            }
        }
        
        /// <remarks/>
        public string csCollector {
            get {
                return this.csCollectorField;
            }
            set {
                this.csCollectorField = value;
            }
        }
        
        /// <remarks/>
        public long csFcId {
            get {
                return this.csFcIdField;
            }
            set {
                this.csFcIdField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool csFcIdSpecified {
            get {
                return this.csFcIdFieldSpecified;
            }
            set {
                this.csFcIdFieldSpecified = value;
            }
        }
        
        /// <remarks/>
        public string csFcIdPub {
            get {
                return this.csFcIdPubField;
            }
            set {
                this.csFcIdPubField = value;
            }
        }
        
        /// <remarks/>
        public money csCscurbalance {
            get {
                return this.csCscurbalanceField;
            }
            set {
                this.csCscurbalanceField = value;
            }
        }
        
        /// <remarks/>
        public money csPrevbalance {
            get {
                return this.csPrevbalanceField;
            }
            set {
                this.csPrevbalanceField = value;
            }
        }
        
        /// <remarks/>
        public money csUnbilledAmount {
            get {
                return this.csUnbilledAmountField;
            }
            set {
                this.csUnbilledAmountField = value;
            }
        }
        
        /// <remarks/>
        public string csPaybehaviour {
            get {
                return this.csPaybehaviourField;
            }
            set {
                this.csPaybehaviourField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(DataType="integer")]
        public string csNoBouncePay {
            get {
                return this.csNoBouncePayField;
            }
            set {
                this.csNoBouncePayField = value;
            }
        }
        
        /// <remarks/>
        public long csDealerid {
            get {
                return this.csDealeridField;
            }
            set {
                this.csDealeridField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool csDealeridSpecified {
            get {
                return this.csDealeridFieldSpecified;
            }
            set {
                this.csDealeridFieldSpecified = value;
            }
        }
        
        /// <remarks/>
        public string csDealeridPub {
            get {
                return this.csDealeridPubField;
            }
            set {
                this.csDealeridPubField = value;
            }
        }
        
        /// <remarks/>
        public bool csInitPrepaidContrOwner {
            get {
                return this.csInitPrepaidContrOwnerField;
            }
            set {
                this.csInitPrepaidContrOwnerField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool csInitPrepaidContrOwnerSpecified {
            get {
                return this.csInitPrepaidContrOwnerFieldSpecified;
            }
            set {
                this.csInitPrepaidContrOwnerFieldSpecified = value;
            }
        }
        
        /// <remarks/>
        public System.DateTime csCreationDate {
            get {
                return this.csCreationDateField;
            }
            set {
                this.csCreationDateField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool csCreationDateSpecified {
            get {
                return this.csCreationDateFieldSpecified;
            }
            set {
                this.csCreationDateFieldSpecified = value;
            }
        }
        
        /// <remarks/>
        public System.DateTime csDeactivationDate {
            get {
                return this.csDeactivationDateField;
            }
            set {
                this.csDeactivationDateField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool csDeactivationDateSpecified {
            get {
                return this.csDeactivationDateFieldSpecified;
            }
            set {
                this.csDeactivationDateFieldSpecified = value;
            }
        }
        
        /// <remarks/>
        public System.DateTime csSuspensionDate {
            get {
                return this.csSuspensionDateField;
            }
            set {
                this.csSuspensionDateField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool csSuspensionDateSpecified {
            get {
                return this.csSuspensionDateFieldSpecified;
            }
            set {
                this.csSuspensionDateFieldSpecified = value;
            }
        }
        
        /// <remarks/>
        public System.DateTime csReactivationDate {
            get {
                return this.csReactivationDateField;
            }
            set {
                this.csReactivationDateField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool csReactivationDateSpecified {
            get {
                return this.csReactivationDateFieldSpecified;
            }
            set {
                this.csReactivationDateFieldSpecified = value;
            }
        }
        
        /// <remarks/>
        public string lastModificationUser {
            get {
                return this.lastModificationUserField;
            }
            set {
                this.lastModificationUserField = value;
            }
        }
        
        /// <remarks/>
        public long paymentRespId {
            get {
                return this.paymentRespIdField;
            }
            set {
                this.paymentRespIdField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool paymentRespIdSpecified {
            get {
                return this.paymentRespIdFieldSpecified;
            }
            set {
                this.paymentRespIdFieldSpecified = value;
            }
        }
        
        /// <remarks/>
        public string csPaymntRespCode {
            get {
                return this.csPaymntRespCodeField;
            }
            set {
                this.csPaymntRespCodeField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlArrayItemAttribute("item", IsNullable=false)]
        public partyRoleAssignmentsListpartResponse[] partyRoleAssignments {
            get {
                return this.partyRoleAssignmentsField;
            }
            set {
                this.partyRoleAssignmentsField = value;
            }
        }
        
        /// <remarks/>
        public string partyType {
            get {
                return this.partyTypeField;
            }
            set {
                this.partyTypeField = value;
            }
        }
        
        /// <remarks/>
        public bool collInd {
            get {
                return this.collIndField;
            }
            set {
                this.collIndField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool collIndSpecified {
            get {
                return this.collIndFieldSpecified;
            }
            set {
                this.collIndFieldSpecified = value;
            }
        }
        
        /// <remarks/>
        public bool markedForRerating {
            get {
                return this.markedForReratingField;
            }
            set {
                this.markedForReratingField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool markedForReratingSpecified {
            get {
                return this.markedForReratingFieldSpecified;
            }
            set {
                this.markedForReratingFieldSpecified = value;
            }
        }
        
        /// <remarks/>
        public string externalCustomerId {
            get {
                return this.externalCustomerIdField;
            }
            set {
                this.externalCustomerIdField = value;
            }
        }
        
        /// <remarks/>
        public string externalCustomerSetId {
            get {
                return this.externalCustomerSetIdField;
            }
            set {
                this.externalCustomerSetIdField = value;
            }
        }
        
        /// <remarks/>
        public long maxCsLevel {
            get {
                return this.maxCsLevelField;
            }
            set {
                this.maxCsLevelField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool maxCsLevelSpecified {
            get {
                return this.maxCsLevelFieldSpecified;
            }
            set {
                this.maxCsLevelFieldSpecified = value;
            }
        }
        
        /// <remarks/>
        public string creditScore {
            get {
                return this.creditScoreField;
            }
            set {
                this.creditScoreField = value;
            }
        }
        
        /// <remarks/>
        public string creditScoreProvider {
            get {
                return this.creditScoreProviderField;
            }
            set {
                this.creditScoreProviderField = value;
            }
        }
        
        /// <remarks/>
        public string csCscreditUser {
            get {
                return this.csCscreditUserField;
            }
            set {
                this.csCscreditUserField = value;
            }
        }
        
        /// <remarks/>
        public bool performCreditScoring {
            get {
                return this.performCreditScoringField;
            }
            set {
                this.performCreditScoringField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool performCreditScoringSpecified {
            get {
                return this.performCreditScoringFieldSpecified;
            }
            set {
                this.performCreditScoringFieldSpecified = value;
            }
        }
        
        /// <remarks/>
        public string cslvlname {
            get {
                return this.cslvlnameField;
            }
            set {
                this.cslvlnameField = value;
            }
        }
        
        /// <remarks/>
        public long adrNationality {
            get {
                return this.adrNationalityField;
            }
            set {
                this.adrNationalityField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool adrNationalitySpecified {
            get {
                return this.adrNationalityFieldSpecified;
            }
            set {
                this.adrNationalityFieldSpecified = value;
            }
        }
        
        /// <remarks/>
        public string adrNationalityPub {
            get {
                return this.adrNationalityPubField;
            }
            set {
                this.adrNationalityPubField = value;
            }
        }
        
        /// <remarks/>
        public bool adrEmployee {
            get {
                return this.adrEmployeeField;
            }
            set {
                this.adrEmployeeField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool adrEmployeeSpecified {
            get {
                return this.adrEmployeeFieldSpecified;
            }
            set {
                this.adrEmployeeFieldSpecified = value;
            }
        }
        
        /// <remarks/>
        public string csTestbillrun {
            get {
                return this.csTestbillrunField;
            }
            set {
                this.csTestbillrunField = value;
            }
        }
        
        /// <remarks/>
        public string roundingCarryLeftOver {
            get {
                return this.roundingCarryLeftOverField;
            }
            set {
                this.roundingCarryLeftOverField = value;
            }
        }
        
        /// <remarks/>
        public bool allowIndividualBillcycleInd {
            get {
                return this.allowIndividualBillcycleIndField;
            }
            set {
                this.allowIndividualBillcycleIndField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool allowIndividualBillcycleIndSpecified {
            get {
                return this.allowIndividualBillcycleIndFieldSpecified;
            }
            set {
                this.allowIndividualBillcycleIndFieldSpecified = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.7.2556.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://ericsson.com/services/ws_CIL_7/sessionchange")]
    public partial class valuesListpartRequest {
        
        private string keyField;
        
        private string valueField;
        
        /// <remarks/>
        public string key {
            get {
                return this.keyField;
            }
            set {
                this.keyField = value;
            }
        }
        
        /// <remarks/>
        public string value {
            get {
                return this.valueField;
            }
            set {
                this.valueField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.7.2556.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://ericsson.com/services/ws_CIL_7/sessionchange")]
    public partial class sessionChangeRequest {
        
        private valuesListpartRequest[] valuesField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlArrayItemAttribute("item", IsNullable=false)]
        public valuesListpartRequest[] values {
            get {
                return this.valuesField;
            }
            set {
                this.valuesField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.7.2556.0")]
    public delegate void customerReadCompletedEventHandler(object sender, customerReadCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.7.2556.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class customerReadCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal customerReadCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public customerReadResponse Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((customerReadResponse)(this.results[0]));
            }
        }
    }
}

#pragma warning restore 1591