using AmxPeruCommonLibrary.ServiceContracts.Model;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Text;
using System.Threading.Tasks;

namespace AmxPeruCommonLibrary.ServiceContracts.Services
{
    //------------------------------------------------------------------------------
    // <auto-generated>
    //     This code was generated by a tool.
    //     Runtime Version:4.0.30319.42000
    //
    //     Changes to this file may cause incorrect behavior and will be lost if
    //     the code is regenerated.
    // </auto-generated>
    //------------------------------------------------------------------------------



    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(Namespace = "http://ericsson.com/services/ws_CIL_7", ConfigurationName = "NkRemainingSuspensionDaysReadService")]
    public interface NkRemainingSuspensionDaysReadService
    {

        // CODEGEN: Generating message contract since the operation nkRemainingSuspensionDaysRead is neither RPC nor document wrapped.
        [System.ServiceModel.OperationContractAttribute(Action = "", ReplyAction = "*")]
        [System.ServiceModel.XmlSerializerFormatAttribute()]
        nkRemainingSuspensionDaysReadResponse1 nkRemainingSuspensionDaysRead(nkRemainingSuspensionDaysReadRequest1 request);

        [System.ServiceModel.OperationContractAttribute(Action = "", ReplyAction = "*")]
        System.Threading.Tasks.Task<nkRemainingSuspensionDaysReadResponse1> nkRemainingSuspensionDaysReadAsync(nkRemainingSuspensionDaysReadRequest1 request);
    }

    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("svcutil", "4.6.1055.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace = "http://ericsson.com/services/ws_CIL_7/nkremainingsuspensiondaysread")]
    public partial class nkRemainingSuspensionDaysReadRequest
    {

        private inputAttributes inputAttributesField;

        private sessionChangeRequest sessionChangeRequestField;

        /// <remarks/>
        public inputAttributes inputAttributes
        {
            get
            {
                return this.inputAttributesField;
            }
            set
            {
                this.inputAttributesField = value;
            }
        }

        /// <remarks/>
        public sessionChangeRequest sessionChangeRequest
        {
            get
            {
                return this.sessionChangeRequestField;
            }
            set
            {
                this.sessionChangeRequestField = value;
            }
        }
    }


    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("svcutil", "4.6.1055.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace = "http://ericsson.com/services/ws_CIL_7/nkremainingsuspensiondaysread")]
    public partial class nkRemainingSuspensionDaysReadResponse
    {

        private long coIdField;

        private bool coIdFieldSpecified;

        private string coIdPubField;

        private string dirnumField;

        private string numRemainSuspensionDayField;

        /// <remarks/>
        public long coId
        {
            get
            {
                return this.coIdField;
            }
            set
            {
                this.coIdField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool coIdSpecified
        {
            get
            {
                return this.coIdFieldSpecified;
            }
            set
            {
                this.coIdFieldSpecified = value;
            }
        }

        /// <remarks/>
        public string coIdPub
        {
            get
            {
                return this.coIdPubField;
            }
            set
            {
                this.coIdPubField = value;
            }
        }

        /// <remarks/>
        public string dirnum
        {
            get
            {
                return this.dirnumField;
            }
            set
            {
                this.dirnumField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(DataType = "integer")]
        public string numRemainSuspensionDay
        {
            get
            {
                return this.numRemainSuspensionDayField;
            }
            set
            {
                this.numRemainSuspensionDayField = value;
            }
        }
    }


    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped = false)]
    public partial class nkRemainingSuspensionDaysReadRequest1
    {

        [System.ServiceModel.MessageBodyMemberAttribute(Namespace = "http://ericsson.com/services/ws_CIL_7/nkremainingsuspensiondaysread", Order = 0)]
        public nkRemainingSuspensionDaysReadRequest nkRemainingSuspensionDaysReadRequest;

        public nkRemainingSuspensionDaysReadRequest1()
        {
        }

        public nkRemainingSuspensionDaysReadRequest1(nkRemainingSuspensionDaysReadRequest nkRemainingSuspensionDaysReadRequest)
        {
            this.nkRemainingSuspensionDaysReadRequest = nkRemainingSuspensionDaysReadRequest;
        }
    }

    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped = false)]
    public partial class nkRemainingSuspensionDaysReadResponse1
    {

        [System.ServiceModel.MessageBodyMemberAttribute(Namespace = "http://ericsson.com/services/ws_CIL_7/nkremainingsuspensiondaysread", Order = 0)]
        public nkRemainingSuspensionDaysReadResponse nkRemainingSuspensionDaysReadResponse;

        public nkRemainingSuspensionDaysReadResponse1()
        {
        }

        public nkRemainingSuspensionDaysReadResponse1(nkRemainingSuspensionDaysReadResponse nkRemainingSuspensionDaysReadResponse)
        {
            this.nkRemainingSuspensionDaysReadResponse = nkRemainingSuspensionDaysReadResponse;
        }
    }

    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface NkRemainingSuspensionDaysReadServiceChannel : NkRemainingSuspensionDaysReadService, System.ServiceModel.IClientChannel
    {
    }

    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class NkRemainingSuspensionDaysReadServiceClient : System.ServiceModel.ClientBase<NkRemainingSuspensionDaysReadService>, NkRemainingSuspensionDaysReadService
    {

        public NkRemainingSuspensionDaysReadServiceClient()
        {
        }

        public NkRemainingSuspensionDaysReadServiceClient(string endpointConfigurationName) :
                base(endpointConfigurationName)
        {
        }

        public NkRemainingSuspensionDaysReadServiceClient(string endpointConfigurationName, string remoteAddress) :
                base(endpointConfigurationName, remoteAddress)
        {
        }

        public NkRemainingSuspensionDaysReadServiceClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) :
                base(endpointConfigurationName, remoteAddress)
        {
        }

        public NkRemainingSuspensionDaysReadServiceClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) :
                base(binding, remoteAddress)
        {
        }

        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        nkRemainingSuspensionDaysReadResponse1 NkRemainingSuspensionDaysReadService.nkRemainingSuspensionDaysRead(nkRemainingSuspensionDaysReadRequest1 request)
        {
            return base.Channel.nkRemainingSuspensionDaysRead(request);
        }

        public nkRemainingSuspensionDaysReadResponse nkRemainingSuspensionDaysRead(nkRemainingSuspensionDaysReadRequest nkRemainingSuspensionDaysReadRequest)
        {
            nkRemainingSuspensionDaysReadRequest1 inValue = new nkRemainingSuspensionDaysReadRequest1();
            inValue.nkRemainingSuspensionDaysReadRequest = nkRemainingSuspensionDaysReadRequest;
            nkRemainingSuspensionDaysReadResponse1 retVal = ((NkRemainingSuspensionDaysReadService)(this)).nkRemainingSuspensionDaysRead(inValue);
            return retVal.nkRemainingSuspensionDaysReadResponse;
        }

        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<nkRemainingSuspensionDaysReadResponse1> NkRemainingSuspensionDaysReadService.nkRemainingSuspensionDaysReadAsync(nkRemainingSuspensionDaysReadRequest1 request)
        {
            return base.Channel.nkRemainingSuspensionDaysReadAsync(request);
        }

        public System.Threading.Tasks.Task<nkRemainingSuspensionDaysReadResponse1> nkRemainingSuspensionDaysReadAsync(nkRemainingSuspensionDaysReadRequest nkRemainingSuspensionDaysReadRequest)
        {
            nkRemainingSuspensionDaysReadRequest1 inValue = new nkRemainingSuspensionDaysReadRequest1();
            inValue.nkRemainingSuspensionDaysReadRequest = nkRemainingSuspensionDaysReadRequest;
            return ((NkRemainingSuspensionDaysReadService)(this)).nkRemainingSuspensionDaysReadAsync(inValue);
        }
    }

}
