//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------



using AmxPeruCommonLibrary.ServiceContracts.Model;

[System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
[System.ServiceModel.ServiceContractAttribute(Namespace = "http://ericsson.com/services/ws_CIL_7", ConfigurationName = "ProductCfsReadService")]
public interface ProductCfsReadService
{

    // CODEGEN: Generating message contract since the operation productCfsRead is neither RPC nor document wrapped.
    [System.ServiceModel.OperationContractAttribute(Action = "", ReplyAction = "*")]
    [System.ServiceModel.XmlSerializerFormatAttribute()]
    productCfsReadResponse1 productCfsRead(productCfsReadRequest1 request);

    [System.ServiceModel.OperationContractAttribute(Action = "", ReplyAction = "*")]
    System.Threading.Tasks.Task<productCfsReadResponse1> productCfsReadAsync(productCfsReadRequest1 request);
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("svcutil", "4.6.1055.0")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.XmlTypeAttribute(Namespace = "http://ericsson.com/services/ws_CIL_7/productcfsread")]
public partial class productCfsReadRequest
{

    private inputAttributes inputAttributesField;

    private sessionChangeRequest sessionChangeRequestField;

    /// <remarks/>
    public inputAttributes inputAttributes
    {
        get
        {
            return this.inputAttributesField;
        }
        set
        {
            this.inputAttributesField = value;
        }
    }

    /// <remarks/>
    public sessionChangeRequest sessionChangeRequest
    {
        get
        {
            return this.sessionChangeRequestField;
        }
        set
        {
            this.sessionChangeRequestField = value;
        }
    }
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("svcutil", "4.6.1055.0")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.XmlTypeAttribute(Namespace = "http://ericsson.com/services/ws_CIL_7/productcfsread")]
public partial class balanceOutputDTO
{

    private string balanceSpecificationIdField;

    private string cfssIdField;

    private long accountIdField;

    private bool accountIdFieldSpecified;

    private string accountTypeField;

    private double thresholdField;

    private bool thresholdFieldSpecified;

    private characteristicValueDTO[] characteristicsField;

    /// <remarks/>
    public string balanceSpecificationId
    {
        get
        {
            return this.balanceSpecificationIdField;
        }
        set
        {
            this.balanceSpecificationIdField = value;
        }
    }

    /// <remarks/>
    public string cfssId
    {
        get
        {
            return this.cfssIdField;
        }
        set
        {
            this.cfssIdField = value;
        }
    }

    /// <remarks/>
    public long accountId
    {
        get
        {
            return this.accountIdField;
        }
        set
        {
            this.accountIdField = value;
        }
    }

    /// <remarks/>
    [System.Xml.Serialization.XmlIgnoreAttribute()]
    public bool accountIdSpecified
    {
        get
        {
            return this.accountIdFieldSpecified;
        }
        set
        {
            this.accountIdFieldSpecified = value;
        }
    }

    /// <remarks/>
    public string accountType
    {
        get
        {
            return this.accountTypeField;
        }
        set
        {
            this.accountTypeField = value;
        }
    }

    /// <remarks/>
    public double threshold
    {
        get
        {
            return this.thresholdField;
        }
        set
        {
            this.thresholdField = value;
        }
    }

    /// <remarks/>
    [System.Xml.Serialization.XmlIgnoreAttribute()]
    public bool thresholdSpecified
    {
        get
        {
            return this.thresholdFieldSpecified;
        }
        set
        {
            this.thresholdFieldSpecified = value;
        }
    }

    /// <remarks/>
    [System.Xml.Serialization.XmlArrayItemAttribute(IsNullable = false)]
    public characteristicValueDTO[] characteristics
    {
        get
        {
            return this.characteristicsField;
        }
        set
        {
            this.characteristicsField = value;
        }
    }
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("svcutil", "4.6.1055.0")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.XmlTypeAttribute(Namespace = "http://ericsson.com/services/ws_CIL_7/productcfsread")]
public partial class characteristicValueDTO
{

    private string characteristicShortDescriptionField;

    private string valueField;

    private characteristicMultiValueDTO[] multiValuesField;

    /// <remarks/>
    public string characteristicShortDescription
    {
        get
        {
            return this.characteristicShortDescriptionField;
        }
        set
        {
            this.characteristicShortDescriptionField = value;
        }
    }

    /// <remarks/>
    public string value
    {
        get
        {
            return this.valueField;
        }
        set
        {
            this.valueField = value;
        }
    }

    /// <remarks/>
    [System.Xml.Serialization.XmlArrayItemAttribute(IsNullable = false)]
    public characteristicMultiValueDTO[] multiValues
    {
        get
        {
            return this.multiValuesField;
        }
        set
        {
            this.multiValuesField = value;
        }
    }
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("svcutil", "4.6.1055.0")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.XmlTypeAttribute(Namespace = "http://ericsson.com/services/ws_CIL_7/productcfsread")]
public partial class characteristicMultiValueDTO
{

    private long seqField;

    private bool seqFieldSpecified;

    private string valueField;

    /// <remarks/>
    public long seq
    {
        get
        {
            return this.seqField;
        }
        set
        {
            this.seqField = value;
        }
    }

    /// <remarks/>
    [System.Xml.Serialization.XmlIgnoreAttribute()]
    public bool seqSpecified
    {
        get
        {
            return this.seqFieldSpecified;
        }
        set
        {
            this.seqFieldSpecified = value;
        }
    }

    /// <remarks/>
    public string value
    {
        get
        {
            return this.valueField;
        }
        set
        {
            this.valueField = value;
        }
    }
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("svcutil", "4.6.1055.0")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.XmlTypeAttribute(Namespace = "http://ericsson.com/services/ws_CIL_7/productcfsread")]
public partial class productPopOutputDTO
{

    private string popIdField;

    private characteristicValueDTO[] characteristicsField;

    /// <remarks/>
    public string popId
    {
        get
        {
            return this.popIdField;
        }
        set
        {
            this.popIdField = value;
        }
    }

    /// <remarks/>
    [System.Xml.Serialization.XmlArrayItemAttribute(IsNullable = false)]
    public characteristicValueDTO[] characteristics
    {
        get
        {
            return this.characteristicsField;
        }
        set
        {
            this.characteristicsField = value;
        }
    }
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("svcutil", "4.6.1055.0")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.XmlTypeAttribute(Namespace = "http://ericsson.com/services/ws_CIL_7/productcfsread")]
public partial class productCfsReadCFSOutputDTO
{

    private string cfssIdField;

    private string cfsStatusField;

    private System.DateTime cfsEffectiveDateField;

    private bool cfsEffectiveDateFieldSpecified;

    private characteristicValueDTO[] characteristicsField;

    /// <remarks/>
    public string cfssId
    {
        get
        {
            return this.cfssIdField;
        }
        set
        {
            this.cfssIdField = value;
        }
    }

    /// <remarks/>
    public string cfsStatus
    {
        get
        {
            return this.cfsStatusField;
        }
        set
        {
            this.cfsStatusField = value;
        }
    }

    /// <remarks/>
    public System.DateTime cfsEffectiveDate
    {
        get
        {
            return this.cfsEffectiveDateField;
        }
        set
        {
            this.cfsEffectiveDateField = value;
        }
    }

    /// <remarks/>
    [System.Xml.Serialization.XmlIgnoreAttribute()]
    public bool cfsEffectiveDateSpecified
    {
        get
        {
            return this.cfsEffectiveDateFieldSpecified;
        }
        set
        {
            this.cfsEffectiveDateFieldSpecified = value;
        }
    }

    /// <remarks/>
    [System.Xml.Serialization.XmlArrayItemAttribute(IsNullable = false)]
    public characteristicValueDTO[] characteristics
    {
        get
        {
            return this.characteristicsField;
        }
        set
        {
            this.characteristicsField = value;
        }
    }
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("svcutil", "4.6.1055.0")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.XmlTypeAttribute(Namespace = "http://ericsson.com/services/ws_CIL_7/productcfsread")]
public partial class productCfsReadResourcesOutputDTO
{

    private string numberField;

    private string numberingPlanCodePubField;

    private string resourceSpecificationIdField;

    private string cfssIdField;

    private characteristicValueDTO[] characteristicsField;

    /// <remarks/>
    public string number
    {
        get
        {
            return this.numberField;
        }
        set
        {
            this.numberField = value;
        }
    }

    /// <remarks/>
    public string numberingPlanCodePub
    {
        get
        {
            return this.numberingPlanCodePubField;
        }
        set
        {
            this.numberingPlanCodePubField = value;
        }
    }

    /// <remarks/>
    public string resourceSpecificationId
    {
        get
        {
            return this.resourceSpecificationIdField;
        }
        set
        {
            this.resourceSpecificationIdField = value;
        }
    }

    /// <remarks/>
    public string cfssId
    {
        get
        {
            return this.cfssIdField;
        }
        set
        {
            this.cfssIdField = value;
        }
    }

    /// <remarks/>
    [System.Xml.Serialization.XmlArrayItemAttribute(IsNullable = false)]
    public characteristicValueDTO[] characteristics
    {
        get
        {
            return this.characteristicsField;
        }
        set
        {
            this.characteristicsField = value;
        }
    }
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("svcutil", "4.6.1055.0")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.XmlTypeAttribute(Namespace = "http://ericsson.com/services/ws_CIL_7/productcfsread")]
public partial class productCfsReadOutputProductDTO
{

    private string productIdField;

    private string productOfferingIdField;

    private string parentProductIdField;

    private bool bundledProductOfferingIndField;

    private bool bundledProductOfferingIndFieldSpecified;

    private string productOfferingTypeField;

    private string productStatusField;

    private System.DateTime effectiveDateField;

    private bool effectiveDateFieldSpecified;

    private bool exchangeIndicatorField;

    private bool exchangeIndicatorFieldSpecified;

    private long numberOfMembersField;

    private bool numberOfMembersFieldSpecified;

    private string userReasonField;

    private productCfsReadResourcesOutputDTO[] resourcesField;

    private characteristicValueDTO[] characteristicsField;

    private productCfsReadCFSOutputDTO[] cfsField;

    private productPopOutputDTO[] popsField;

    private balanceOutputDTO[] balancesField;

    /// <remarks/>
    public string productId
    {
        get
        {
            return this.productIdField;
        }
        set
        {
            this.productIdField = value;
        }
    }

    /// <remarks/>
    public string productOfferingId
    {
        get
        {
            return this.productOfferingIdField;
        }
        set
        {
            this.productOfferingIdField = value;
        }
    }

    /// <remarks/>
    public string parentProductId
    {
        get
        {
            return this.parentProductIdField;
        }
        set
        {
            this.parentProductIdField = value;
        }
    }

    /// <remarks/>
    public bool bundledProductOfferingInd
    {
        get
        {
            return this.bundledProductOfferingIndField;
        }
        set
        {
            this.bundledProductOfferingIndField = value;
        }
    }

    /// <remarks/>
    [System.Xml.Serialization.XmlIgnoreAttribute()]
    public bool bundledProductOfferingIndSpecified
    {
        get
        {
            return this.bundledProductOfferingIndFieldSpecified;
        }
        set
        {
            this.bundledProductOfferingIndFieldSpecified = value;
        }
    }

    /// <remarks/>
    public string productOfferingType
    {
        get
        {
            return this.productOfferingTypeField;
        }
        set
        {
            this.productOfferingTypeField = value;
        }
    }

    /// <remarks/>
    public string productStatus
    {
        get
        {
            return this.productStatusField;
        }
        set
        {
            this.productStatusField = value;
        }
    }

    /// <remarks/>
    public System.DateTime effectiveDate
    {
        get
        {
            return this.effectiveDateField;
        }
        set
        {
            this.effectiveDateField = value;
        }
    }

    /// <remarks/>
    [System.Xml.Serialization.XmlIgnoreAttribute()]
    public bool effectiveDateSpecified
    {
        get
        {
            return this.effectiveDateFieldSpecified;
        }
        set
        {
            this.effectiveDateFieldSpecified = value;
        }
    }

    /// <remarks/>
    public bool exchangeIndicator
    {
        get
        {
            return this.exchangeIndicatorField;
        }
        set
        {
            this.exchangeIndicatorField = value;
        }
    }

    /// <remarks/>
    [System.Xml.Serialization.XmlIgnoreAttribute()]
    public bool exchangeIndicatorSpecified
    {
        get
        {
            return this.exchangeIndicatorFieldSpecified;
        }
        set
        {
            this.exchangeIndicatorFieldSpecified = value;
        }
    }

    /// <remarks/>
    public long numberOfMembers
    {
        get
        {
            return this.numberOfMembersField;
        }
        set
        {
            this.numberOfMembersField = value;
        }
    }

    /// <remarks/>
    [System.Xml.Serialization.XmlIgnoreAttribute()]
    public bool numberOfMembersSpecified
    {
        get
        {
            return this.numberOfMembersFieldSpecified;
        }
        set
        {
            this.numberOfMembersFieldSpecified = value;
        }
    }

    /// <remarks/>
    public string userReason
    {
        get
        {
            return this.userReasonField;
        }
        set
        {
            this.userReasonField = value;
        }
    }

    /// <remarks/>
    [System.Xml.Serialization.XmlArrayItemAttribute(IsNullable = false)]
    public productCfsReadResourcesOutputDTO[] resources
    {
        get
        {
            return this.resourcesField;
        }
        set
        {
            this.resourcesField = value;
        }
    }

    /// <remarks/>
    [System.Xml.Serialization.XmlArrayItemAttribute(IsNullable = false)]
    public characteristicValueDTO[] characteristics
    {
        get
        {
            return this.characteristicsField;
        }
        set
        {
            this.characteristicsField = value;
        }
    }

    /// <remarks/>
    [System.Xml.Serialization.XmlArrayItemAttribute(IsNullable = false)]
    public productCfsReadCFSOutputDTO[] cfs
    {
        get
        {
            return this.cfsField;
        }
        set
        {
            this.cfsField = value;
        }
    }

    /// <remarks/>
    [System.Xml.Serialization.XmlArrayItemAttribute(IsNullable = false)]
    public productPopOutputDTO[] pops
    {
        get
        {
            return this.popsField;
        }
        set
        {
            this.popsField = value;
        }
    }

    /// <remarks/>
    [System.Xml.Serialization.XmlArrayItemAttribute(IsNullable = false)]
    public balanceOutputDTO[] balances
    {
        get
        {
            return this.balancesField;
        }
        set
        {
            this.balancesField = value;
        }
    }
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("svcutil", "4.6.1055.0")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.XmlTypeAttribute(Namespace = "http://ericsson.com/services/ws_CIL_7/productcfsread")]
public partial class productCfsReadOutputDTO
{

    private string contractIdPubField;

    private productCfsReadOutputProductDTO[] productsField;

    /// <remarks/>
    public string contractIdPub
    {
        get
        {
            return this.contractIdPubField;
        }
        set
        {
            this.contractIdPubField = value;
        }
    }

    /// <remarks/>
    [System.Xml.Serialization.XmlArrayItemAttribute(IsNullable = false)]
    public productCfsReadOutputProductDTO[] products
    {
        get
        {
            return this.productsField;
        }
        set
        {
            this.productsField = value;
        }
    }
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("svcutil", "4.6.1055.0")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.XmlTypeAttribute(Namespace = "http://ericsson.com/services/ws_CIL_7/productcfsread")]
public partial class productCfsReadResponse
{

    private productCfsReadOutputDTO productCfsReadOutputDTOField;

    /// <remarks/>
    public productCfsReadOutputDTO productCfsReadOutputDTO
    {
        get
        {
            return this.productCfsReadOutputDTOField;
        }
        set
        {
            this.productCfsReadOutputDTOField = value;
        }
    }
}



[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
[System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
[System.ServiceModel.MessageContractAttribute(IsWrapped = false)]
public partial class productCfsReadRequest1
{

    [System.ServiceModel.MessageBodyMemberAttribute(Namespace = "http://ericsson.com/services/ws_CIL_7/productcfsread", Order = 0)]
    public productCfsReadRequest productCfsReadRequest;

    public productCfsReadRequest1()
    {
    }

    public productCfsReadRequest1(productCfsReadRequest productCfsReadRequest)
    {
        this.productCfsReadRequest = productCfsReadRequest;
    }
}

[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
[System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
[System.ServiceModel.MessageContractAttribute(IsWrapped = false)]
public partial class productCfsReadResponse1
{

    [System.ServiceModel.MessageBodyMemberAttribute(Namespace = "http://ericsson.com/services/ws_CIL_7/productcfsread", Order = 0)]
    public productCfsReadResponse productCfsReadResponse;

    public productCfsReadResponse1()
    {
    }

    public productCfsReadResponse1(productCfsReadResponse productCfsReadResponse)
    {
        this.productCfsReadResponse = productCfsReadResponse;
    }
}

[System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
public interface ProductCfsReadServiceChannel : ProductCfsReadService, System.ServiceModel.IClientChannel
{
}

[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
public partial class ProductCfsReadServiceClient : System.ServiceModel.ClientBase<ProductCfsReadService>, ProductCfsReadService
{

    public ProductCfsReadServiceClient()
    {
    }

    public ProductCfsReadServiceClient(string endpointConfigurationName) :
            base(endpointConfigurationName)
    {
    }

    public ProductCfsReadServiceClient(string endpointConfigurationName, string remoteAddress) :
            base(endpointConfigurationName, remoteAddress)
    {
    }

    public ProductCfsReadServiceClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) :
            base(endpointConfigurationName, remoteAddress)
    {
    }

    public ProductCfsReadServiceClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) :
            base(binding, remoteAddress)
    {
    }

    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    productCfsReadResponse1 ProductCfsReadService.productCfsRead(productCfsReadRequest1 request)
    {
        return base.Channel.productCfsRead(request);
    }

    public productCfsReadResponse productCfsRead(productCfsReadRequest productCfsReadRequest)
    {
        productCfsReadRequest1 inValue = new productCfsReadRequest1();
        inValue.productCfsReadRequest = productCfsReadRequest;
        productCfsReadResponse1 retVal = ((ProductCfsReadService)(this)).productCfsRead(inValue);
        return retVal.productCfsReadResponse;
    }

    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    System.Threading.Tasks.Task<productCfsReadResponse1> ProductCfsReadService.productCfsReadAsync(productCfsReadRequest1 request)
    {
        return base.Channel.productCfsReadAsync(request);
    }

    public System.Threading.Tasks.Task<productCfsReadResponse1> productCfsReadAsync(productCfsReadRequest productCfsReadRequest)
    {
        productCfsReadRequest1 inValue = new productCfsReadRequest1();
        inValue.productCfsReadRequest = productCfsReadRequest;
        return ((ProductCfsReadService)(this)).productCfsReadAsync(inValue);
    }
}
