//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AmxSoapServicesActivities.StorageMediumRead {
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(Namespace="http://ericsson.com/services/ws_CIL_7", ConfigurationName="StorageMediumRead.StorageMediumReadService")]
    public interface StorageMediumReadService {
        
        // CODEGEN: Generating message contract since the operation storageMediumRead is neither RPC nor document wrapped.
        [System.ServiceModel.OperationContractAttribute(Action="", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        AmxSoapServicesActivities.StorageMediumRead.storageMediumReadResponse1 storageMediumRead(AmxSoapServicesActivities.StorageMediumRead.storageMediumReadRequest1 request);
        
        [System.ServiceModel.OperationContractAttribute(Action="", ReplyAction="*")]
        System.Threading.Tasks.Task<AmxSoapServicesActivities.StorageMediumRead.storageMediumReadResponse1> storageMediumReadAsync(AmxSoapServicesActivities.StorageMediumRead.storageMediumReadRequest1 request);
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.7.2612.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://ericsson.com/services/ws_CIL_7/storagemediumread")]
    public partial class storageMediumReadRequest : object, System.ComponentModel.INotifyPropertyChanged {
        
        private inputAttributes inputAttributesField;
        
        private sessionChangeRequest sessionChangeRequestField;
        
        /// <remarks/>
        public inputAttributes inputAttributes {
            get {
                return this.inputAttributesField;
            }
            set {
                this.inputAttributesField = value;
                this.RaisePropertyChanged("inputAttributes");
            }
        }
        
        /// <remarks/>
        public sessionChangeRequest sessionChangeRequest {
            get {
                return this.sessionChangeRequestField;
            }
            set {
                this.sessionChangeRequestField = value;
                this.RaisePropertyChanged("sessionChangeRequest");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.7.2612.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://ericsson.com/services/ws_CIL_7/storagemediumread")]
    public partial class inputAttributes : object, System.ComponentModel.INotifyPropertyChanged {
        
        private storageMediumReadInputDTO storageMediumReadInputDTOField;
        
        /// <remarks/>
        public storageMediumReadInputDTO storageMediumReadInputDTO {
            get {
                return this.storageMediumReadInputDTOField;
            }
            set {
                this.storageMediumReadInputDTOField = value;
                this.RaisePropertyChanged("storageMediumReadInputDTO");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.7.2612.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://ericsson.com/services/ws_CIL_7/storagemediumread")]
    public partial class storageMediumReadInputDTO : object, System.ComponentModel.INotifyPropertyChanged {
        
        private long idField;
        
        /// <remarks/>
        public long id {
            get {
                return this.idField;
            }
            set {
                this.idField = value;
                this.RaisePropertyChanged("id");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.7.2612.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://ericsson.com/services/ws_CIL_7/storagemediumread")]
    public partial class storageMediumReadOutputDTO : object, System.ComponentModel.INotifyPropertyChanged {
        
        private string serialNumberField;
        
        private long myTemplateField;
        
        private bool myTemplateFieldSpecified;
        
        private long dealerField;
        
        private bool dealerFieldSpecified;
        
        private long hlCodeField;
        
        private bool hlCodeFieldSpecified;
        
        private long npCodeField;
        
        private bool npCodeFieldSpecified;
        
        private string stateField;
        
        private long idField;
        
        private bool idFieldSpecified;
        
        private long numberField;
        
        private bool numberFieldSpecified;
        
        private string portNumberField;
        
        private string pinField;
        
        private string pin2Field;
        
        private string pukField;
        
        private string puk2Field;
        
        private string authenticationKeyField;
        
        private long portIdField;
        
        private bool portIdFieldSpecified;
        
        private string portStatusField;
        
        /// <remarks/>
        public string serialNumber {
            get {
                return this.serialNumberField;
            }
            set {
                this.serialNumberField = value;
                this.RaisePropertyChanged("serialNumber");
            }
        }
        
        /// <remarks/>
        public long myTemplate {
            get {
                return this.myTemplateField;
            }
            set {
                this.myTemplateField = value;
                this.RaisePropertyChanged("myTemplate");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool myTemplateSpecified {
            get {
                return this.myTemplateFieldSpecified;
            }
            set {
                this.myTemplateFieldSpecified = value;
                this.RaisePropertyChanged("myTemplateSpecified");
            }
        }
        
        /// <remarks/>
        public long dealer {
            get {
                return this.dealerField;
            }
            set {
                this.dealerField = value;
                this.RaisePropertyChanged("dealer");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool dealerSpecified {
            get {
                return this.dealerFieldSpecified;
            }
            set {
                this.dealerFieldSpecified = value;
                this.RaisePropertyChanged("dealerSpecified");
            }
        }
        
        /// <remarks/>
        public long hlCode {
            get {
                return this.hlCodeField;
            }
            set {
                this.hlCodeField = value;
                this.RaisePropertyChanged("hlCode");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool hlCodeSpecified {
            get {
                return this.hlCodeFieldSpecified;
            }
            set {
                this.hlCodeFieldSpecified = value;
                this.RaisePropertyChanged("hlCodeSpecified");
            }
        }
        
        /// <remarks/>
        public long npCode {
            get {
                return this.npCodeField;
            }
            set {
                this.npCodeField = value;
                this.RaisePropertyChanged("npCode");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool npCodeSpecified {
            get {
                return this.npCodeFieldSpecified;
            }
            set {
                this.npCodeFieldSpecified = value;
                this.RaisePropertyChanged("npCodeSpecified");
            }
        }
        
        /// <remarks/>
        public string state {
            get {
                return this.stateField;
            }
            set {
                this.stateField = value;
                this.RaisePropertyChanged("state");
            }
        }
        
        /// <remarks/>
        public long id {
            get {
                return this.idField;
            }
            set {
                this.idField = value;
                this.RaisePropertyChanged("id");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool idSpecified {
            get {
                return this.idFieldSpecified;
            }
            set {
                this.idFieldSpecified = value;
                this.RaisePropertyChanged("idSpecified");
            }
        }
        
        /// <remarks/>
        public long number {
            get {
                return this.numberField;
            }
            set {
                this.numberField = value;
                this.RaisePropertyChanged("number");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool numberSpecified {
            get {
                return this.numberFieldSpecified;
            }
            set {
                this.numberFieldSpecified = value;
                this.RaisePropertyChanged("numberSpecified");
            }
        }
        
        /// <remarks/>
        public string portNumber {
            get {
                return this.portNumberField;
            }
            set {
                this.portNumberField = value;
                this.RaisePropertyChanged("portNumber");
            }
        }
        
        /// <remarks/>
        public string pin {
            get {
                return this.pinField;
            }
            set {
                this.pinField = value;
                this.RaisePropertyChanged("pin");
            }
        }
        
        /// <remarks/>
        public string pin2 {
            get {
                return this.pin2Field;
            }
            set {
                this.pin2Field = value;
                this.RaisePropertyChanged("pin2");
            }
        }
        
        /// <remarks/>
        public string puk {
            get {
                return this.pukField;
            }
            set {
                this.pukField = value;
                this.RaisePropertyChanged("puk");
            }
        }
        
        /// <remarks/>
        public string puk2 {
            get {
                return this.puk2Field;
            }
            set {
                this.puk2Field = value;
                this.RaisePropertyChanged("puk2");
            }
        }
        
        /// <remarks/>
        public string authenticationKey {
            get {
                return this.authenticationKeyField;
            }
            set {
                this.authenticationKeyField = value;
                this.RaisePropertyChanged("authenticationKey");
            }
        }
        
        /// <remarks/>
        public long portId {
            get {
                return this.portIdField;
            }
            set {
                this.portIdField = value;
                this.RaisePropertyChanged("portId");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool portIdSpecified {
            get {
                return this.portIdFieldSpecified;
            }
            set {
                this.portIdFieldSpecified = value;
                this.RaisePropertyChanged("portIdSpecified");
            }
        }
        
        /// <remarks/>
        public string portStatus {
            get {
                return this.portStatusField;
            }
            set {
                this.portStatusField = value;
                this.RaisePropertyChanged("portStatus");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.7.2612.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://ericsson.com/services/ws_CIL_7/storagemediumread")]
    public partial class storageMediumReadResponse : object, System.ComponentModel.INotifyPropertyChanged {
        
        private storageMediumReadOutputDTO storageMediumReadOutputDTOField;
        
        /// <remarks/>
        public storageMediumReadOutputDTO storageMediumReadOutputDTO {
            get {
                return this.storageMediumReadOutputDTOField;
            }
            set {
                this.storageMediumReadOutputDTOField = value;
                this.RaisePropertyChanged("storageMediumReadOutputDTO");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.7.2612.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://ericsson.com/services/ws_CIL_7/sessionchange")]
    public partial class valuesListpartRequest : object, System.ComponentModel.INotifyPropertyChanged {
        
        private string keyField;
        
        private string valueField;
        
        /// <remarks/>
        public string key {
            get {
                return this.keyField;
            }
            set {
                this.keyField = value;
                this.RaisePropertyChanged("key");
            }
        }
        
        /// <remarks/>
        public string value {
            get {
                return this.valueField;
            }
            set {
                this.valueField = value;
                this.RaisePropertyChanged("value");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.7.2612.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://ericsson.com/services/ws_CIL_7/sessionchange")]
    public partial class sessionChangeRequest : object, System.ComponentModel.INotifyPropertyChanged {
        
        private valuesListpartRequest[] valuesField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlArrayItemAttribute("item", IsNullable=false)]
        public valuesListpartRequest[] values {
            get {
                return this.valuesField;
            }
            set {
                this.valuesField = value;
                this.RaisePropertyChanged("values");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class storageMediumReadRequest1 {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://ericsson.com/services/ws_CIL_7/storagemediumread", Order=0)]
        public AmxSoapServicesActivities.StorageMediumRead.storageMediumReadRequest storageMediumReadRequest;
        
        public storageMediumReadRequest1() {
        }
        
        public storageMediumReadRequest1(AmxSoapServicesActivities.StorageMediumRead.storageMediumReadRequest storageMediumReadRequest) {
            this.storageMediumReadRequest = storageMediumReadRequest;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class storageMediumReadResponse1 {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://ericsson.com/services/ws_CIL_7/storagemediumread", Order=0)]
        public AmxSoapServicesActivities.StorageMediumRead.storageMediumReadResponse storageMediumReadResponse;
        
        public storageMediumReadResponse1() {
        }
        
        public storageMediumReadResponse1(AmxSoapServicesActivities.StorageMediumRead.storageMediumReadResponse storageMediumReadResponse) {
            this.storageMediumReadResponse = storageMediumReadResponse;
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface StorageMediumReadServiceChannel : AmxSoapServicesActivities.StorageMediumRead.StorageMediumReadService, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class StorageMediumReadServiceClient : System.ServiceModel.ClientBase<AmxSoapServicesActivities.StorageMediumRead.StorageMediumReadService>, AmxSoapServicesActivities.StorageMediumRead.StorageMediumReadService {
        
        public StorageMediumReadServiceClient() {
        }
        
        public StorageMediumReadServiceClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public StorageMediumReadServiceClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public StorageMediumReadServiceClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public StorageMediumReadServiceClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        AmxSoapServicesActivities.StorageMediumRead.storageMediumReadResponse1 AmxSoapServicesActivities.StorageMediumRead.StorageMediumReadService.storageMediumRead(AmxSoapServicesActivities.StorageMediumRead.storageMediumReadRequest1 request) {
            return base.Channel.storageMediumRead(request);
        }
        
        public AmxSoapServicesActivities.StorageMediumRead.storageMediumReadResponse storageMediumRead(AmxSoapServicesActivities.StorageMediumRead.storageMediumReadRequest storageMediumReadRequest) {
            AmxSoapServicesActivities.StorageMediumRead.storageMediumReadRequest1 inValue = new AmxSoapServicesActivities.StorageMediumRead.storageMediumReadRequest1();
            inValue.storageMediumReadRequest = storageMediumReadRequest;
            AmxSoapServicesActivities.StorageMediumRead.storageMediumReadResponse1 retVal = ((AmxSoapServicesActivities.StorageMediumRead.StorageMediumReadService)(this)).storageMediumRead(inValue);
            return retVal.storageMediumReadResponse;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<AmxSoapServicesActivities.StorageMediumRead.storageMediumReadResponse1> AmxSoapServicesActivities.StorageMediumRead.StorageMediumReadService.storageMediumReadAsync(AmxSoapServicesActivities.StorageMediumRead.storageMediumReadRequest1 request) {
            return base.Channel.storageMediumReadAsync(request);
        }
        
        public System.Threading.Tasks.Task<AmxSoapServicesActivities.StorageMediumRead.storageMediumReadResponse1> storageMediumReadAsync(AmxSoapServicesActivities.StorageMediumRead.storageMediumReadRequest storageMediumReadRequest) {
            AmxSoapServicesActivities.StorageMediumRead.storageMediumReadRequest1 inValue = new AmxSoapServicesActivities.StorageMediumRead.storageMediumReadRequest1();
            inValue.storageMediumReadRequest = storageMediumReadRequest;
            return ((AmxSoapServicesActivities.StorageMediumRead.StorageMediumReadService)(this)).storageMediumReadAsync(inValue);
        }
    }
}
