//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AmxPeruPSBActivities.Properties {
    
    
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.VisualStudio.Editors.SettingsDesigner.SettingsSingleFileGenerator", "15.5.0.0")]
    internal sealed partial class Settings : global::System.Configuration.ApplicationSettingsBase {
        
        private static Settings defaultInstance = ((Settings)(global::System.Configuration.ApplicationSettingsBase.Synchronized(new Settings())));
        
        public static Settings Default {
            get {
                return defaultInstance;
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.SpecialSettingAttribute(global::System.Configuration.SpecialSetting.WebServiceUrl)]
        [global::System.Configuration.DefaultSettingValueAttribute("http://www.example.org/")]
        public string AmxPeruPSBActivities_ConsultaEstadoCuenta_v1_ConsultaDeudaCuenta {
            get {
                return ((string)(this["AmxPeruPSBActivities_ConsultaEstadoCuenta_v1_ConsultaDeudaCuenta"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.SpecialSettingAttribute(global::System.Configuration.SpecialSetting.WebServiceUrl)]
        [global::System.Configuration.DefaultSettingValueAttribute("http://www.example.org/")]
        public string AmxPeruPSBActivities_ConsultaDeudaCuenta_v1_ConsultaDeudaCuenta {
            get {
                return ((string)(this["AmxPeruPSBActivities_ConsultaDeudaCuenta_v1_ConsultaDeudaCuenta"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.SpecialSettingAttribute(global::System.Configuration.SpecialSetting.WebServiceUrl)]
        [global::System.Configuration.DefaultSettingValueAttribute("http://www.example.org/")]
        public string AmxPeruPSBActivities_GeneraIncidencia_V1_GeneraIncidencia {
            get {
                return ((string)(this["AmxPeruPSBActivities_GeneraIncidencia_V1_GeneraIncidencia"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.SpecialSettingAttribute(global::System.Configuration.SpecialSetting.WebServiceUrl)]
        [global::System.Configuration.DefaultSettingValueAttribute("http://www.example.com")]
        public string AmxPeruPSBActivities_SendNotification_NotificationManagementLg {
            get {
                return ((string)(this["AmxPeruPSBActivities_SendNotification_NotificationManagementLg"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.SpecialSettingAttribute(global::System.Configuration.SpecialSetting.WebServiceUrl)]
        [global::System.Configuration.DefaultSettingValueAttribute("http://www.example.org/")]
        public string AmxPeruPSBActivities_CargaDocumentoOnBase_V1_CargaDocumentoOnBase {
            get {
                return ((string)(this["AmxPeruPSBActivities_CargaDocumentoOnBase_V1_CargaDocumentoOnBase"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.SpecialSettingAttribute(global::System.Configuration.SpecialSetting.WebServiceUrl)]
        [global::System.Configuration.DefaultSettingValueAttribute("http://www.example.org/")]
        public string AmxPeruPSBActivities_BSS_CUSTOMER_CREDIT_SCORE_MGMT_LG_V1_BSS_CUSTOMER_CREDIT_SCORE_MGMT_LG {
            get {
                return ((string)(this["AmxPeruPSBActivities_BSS_CUSTOMER_CREDIT_SCORE_MGMT_LG_V1_BSS_CUSTOMER_CREDIT_SCO" +
                    "RE_MGMT_LG"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.SpecialSettingAttribute(global::System.Configuration.SpecialSetting.WebServiceUrl)]
        [global::System.Configuration.DefaultSettingValueAttribute("http://www.example.org/")]
        public string AmxPeruPSBActivities_ConsultaEvaluacionCrediticia_V1_consultaEvaluacionCrediticiaSOAP {
            get {
                return ((string)(this["AmxPeruPSBActivities_ConsultaEvaluacionCrediticia_V1_consultaEvaluacionCrediticia" +
                    "SOAP"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.SpecialSettingAttribute(global::System.Configuration.SpecialSetting.WebServiceUrl)]
        [global::System.Configuration.DefaultSettingValueAttribute("http://www.example.org/")]
        public string AmxPeruPSBActivities_ConsultaDocumentoOnBase_V1_consultarDocumentoOnBaseSOAP {
            get {
                return ((string)(this["AmxPeruPSBActivities_ConsultaDocumentoOnBase_V1_consultarDocumentoOnBaseSOAP"]));
            }
        }
    }
}
