//Generated by http://xmltocsharp.azurewebsites.net/

using System;
using System.Collections.Generic;
using System.Linq;
using System.Text;
using System.Threading.Tasks;
using System.Xml.Serialization;

namespace AmxPeruPlugins.Model
{
    [XmlRoot(ElementName = "labelTranslations")]
    public class LabelTranslations5
    {
        [XmlElement(ElementName = "text")]
        public string Text { get; set; }
        [XmlElement(ElementName = "language")]
        public string Language { get; set; }
    }

    [XmlRoot(ElementName = "infoTables")]
    public class InfoTables5
    {
        [XmlElement(ElementName = "infoModelCode")]
        public string InfoModelCode { get; set; }
        [XmlElement(ElementName = "startDate")]
        public string StartDate { get; set; }
        [XmlElement(ElementName = "status")]
        public string Status { get; set; }
        [XmlElement(ElementName = "createDate")]
        public string CreateDate { get; set; }
        [XmlElement(ElementName = "createdBy")]
        public string CreatedBy { get; set; }
        [XmlElement(ElementName = "updateDate")]
        public string UpdateDate { get; set; }
        [XmlElement(ElementName = "updatedBy")]
        public string UpdatedBy { get; set; }
        [XmlElement(ElementName = "projectCode")]
        public string ProjectCode { get; set; }
        [XmlElement(ElementName = "versionCommitDate")]
        public string VersionCommitDate { get; set; }
        [XmlElement(ElementName = "versionId")]
        public string VersionId { get; set; }
        [XmlElement(ElementName = "data")]
        public string Data { get; set; }
        [XmlElement(ElementName = "infoTableCode")]
        public string InfoTableCode { get; set; }
        [XmlElement(ElementName = "label")]
        public string Label { get; set; }
        [XmlElement(ElementName = "labelTranslations")]
        public LabelTranslations5 LabelTranslations { get; set; }
    }

    [XmlRoot(ElementName = "infoTableList")]
    public class InfoTableList5
    {
        [XmlElement(ElementName = "infoTables")]
        public List<InfoTables5> InfoTables { get; set; }
    }

    [XmlRoot(ElementName = "Body", Namespace = "http://schemas.xmlsoap.org/soap/envelope/")]
    public class Body5
    {
        [XmlElement(ElementName = "infoTableList")]
        public InfoTableList5 InfoTableList { get; set; }
    }

    [XmlRoot(ElementName = "Envelope", Namespace = "http://schemas.xmlsoap.org/soap/envelope/")]
    public class Envelope5
    {
        [XmlElement(ElementName = "Header", Namespace = "http://schemas.xmlsoap.org/soap/envelope/")]
        public string Header { get; set; }
        [XmlElement(ElementName = "Body", Namespace = "http://schemas.xmlsoap.org/soap/envelope/")]
        public Body5 Body { get; set; }
        [XmlAttribute(AttributeName = "soapenv", Namespace = "http://www.w3.org/2000/xmlns/")]
        public string Soapenv { get; set; }
    }


}
