//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AmxPeruPSBActivities.TechnicianAppGetResource {
    
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.7.2612.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://www.amx.com/CO/Schema/ClaroFault/v1")]
    public partial class ClaroFault : object, System.ComponentModel.INotifyPropertyChanged {
        
        private string traceabilityIdField;
        
        private ClaroFaultCategoryCode categoryCodeField;
        
        private string categoryDescriptionField;
        
        private string locationField;
        
        private object technicalDescriptionField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=0)]
        public string traceabilityId {
            get {
                return this.traceabilityIdField;
            }
            set {
                this.traceabilityIdField = value;
                this.RaisePropertyChanged("traceabilityId");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=1)]
        public ClaroFaultCategoryCode categoryCode {
            get {
                return this.categoryCodeField;
            }
            set {
                this.categoryCodeField = value;
                this.RaisePropertyChanged("categoryCode");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=2)]
        public string categoryDescription {
            get {
                return this.categoryDescriptionField;
            }
            set {
                this.categoryDescriptionField = value;
                this.RaisePropertyChanged("categoryDescription");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=3)]
        public string location {
            get {
                return this.locationField;
            }
            set {
                this.locationField = value;
                this.RaisePropertyChanged("location");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=4)]
        public object technicalDescription {
            get {
                return this.technicalDescriptionField;
            }
            set {
                this.technicalDescriptionField = value;
                this.RaisePropertyChanged("technicalDescription");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.7.2612.0")]
    [System.SerializableAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true, Namespace="http://www.amx.com/CO/Schema/ClaroFault/v1")]
    public enum ClaroFaultCategoryCode {
        
        /// <remarks/>
        [System.Xml.Serialization.XmlEnumAttribute("01")]
        Item01,
        
        /// <remarks/>
        [System.Xml.Serialization.XmlEnumAttribute("02")]
        Item02,
        
        /// <remarks/>
        [System.Xml.Serialization.XmlEnumAttribute("03")]
        Item03,
        
        /// <remarks/>
        [System.Xml.Serialization.XmlEnumAttribute("04")]
        Item04,
        
        /// <remarks/>
        [System.Xml.Serialization.XmlEnumAttribute("05")]
        Item05,
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.7.2612.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://www.amx.com/CO/Schema/BaseTypeABE/v1")]
    public partial class AttributeValuePair : object, System.ComponentModel.INotifyPropertyChanged {
        
        private string attributeNameField;
        
        private string attributeValueField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=0)]
        public string attributeName {
            get {
                return this.attributeNameField;
            }
            set {
                this.attributeNameField = value;
                this.RaisePropertyChanged("attributeName");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=1)]
        public string attributeValue {
            get {
                return this.attributeValueField;
            }
            set {
                this.attributeValueField = value;
                this.RaisePropertyChanged("attributeValue");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.7.2612.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://www.amx.com/CO/Schema/ClaroHeaders/v1")]
    public partial class HeaderResponse : object, System.ComponentModel.INotifyPropertyChanged {
        
        private System.DateTime responseDateField;
        
        private string traceabilityIdField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=0)]
        public System.DateTime responseDate {
            get {
                return this.responseDateField;
            }
            set {
                this.responseDateField = value;
                this.RaisePropertyChanged("responseDate");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=1)]
        public string traceabilityId {
            get {
                return this.traceabilityIdField;
            }
            set {
                this.traceabilityIdField = value;
                this.RaisePropertyChanged("traceabilityId");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.7.2612.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://www.amx.com/Schema/Operation/GetResource/V1.0")]
    public partial class GetResourceResponse : object, System.ComponentModel.INotifyPropertyChanged {
        
        private HeaderResponse headerResponseField;
        
        private string resultCodeField;
        
        private string errorMsgField;
        
        private AttributeValuePair[] propertiesField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=0)]
        public HeaderResponse headerResponse {
            get {
                return this.headerResponseField;
            }
            set {
                this.headerResponseField = value;
                this.RaisePropertyChanged("headerResponse");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=1)]
        public string resultCode {
            get {
                return this.resultCodeField;
            }
            set {
                this.resultCodeField = value;
                this.RaisePropertyChanged("resultCode");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=2)]
        public string errorMsg {
            get {
                return this.errorMsgField;
            }
            set {
                this.errorMsgField = value;
                this.RaisePropertyChanged("errorMsg");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("Properties", Order=3)]
        public AttributeValuePair[] Properties {
            get {
                return this.propertiesField;
            }
            set {
                this.propertiesField = value;
                this.RaisePropertyChanged("Properties");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.7.2612.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://www.amx.com/CO/Schema/ClaroHeaders/v1")]
    public partial class HeaderRequest : object, System.ComponentModel.INotifyPropertyChanged {
        
        private string transactionIdField;
        
        private string systemField;
        
        private string userField;
        
        private string passwordField;
        
        private System.DateTime requestDateField;
        
        private string ipApplicationField;
        
        private string traceabilityIdField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=0)]
        public string transactionId {
            get {
                return this.transactionIdField;
            }
            set {
                this.transactionIdField = value;
                this.RaisePropertyChanged("transactionId");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=1)]
        public string system {
            get {
                return this.systemField;
            }
            set {
                this.systemField = value;
                this.RaisePropertyChanged("system");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=2)]
        public string user {
            get {
                return this.userField;
            }
            set {
                this.userField = value;
                this.RaisePropertyChanged("user");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=3)]
        public string password {
            get {
                return this.passwordField;
            }
            set {
                this.passwordField = value;
                this.RaisePropertyChanged("password");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=4)]
        public System.DateTime requestDate {
            get {
                return this.requestDateField;
            }
            set {
                this.requestDateField = value;
                this.RaisePropertyChanged("requestDate");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=5)]
        public string ipApplication {
            get {
                return this.ipApplicationField;
            }
            set {
                this.ipApplicationField = value;
                this.RaisePropertyChanged("ipApplication");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=6)]
        public string traceabilityId {
            get {
                return this.traceabilityIdField;
            }
            set {
                this.traceabilityIdField = value;
                this.RaisePropertyChanged("traceabilityId");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.7.2612.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://www.amx.com/Schema/Operation/GetResource/V1.0")]
    public partial class GetResourceRequest : object, System.ComponentModel.INotifyPropertyChanged {
        
        private HeaderRequest headerRequestField;
        
        private string companyField;
        
        private string idField;
        
        private string dateField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=0)]
        public HeaderRequest headerRequest {
            get {
                return this.headerRequestField;
            }
            set {
                this.headerRequestField = value;
                this.RaisePropertyChanged("headerRequest");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=1)]
        public string company {
            get {
                return this.companyField;
            }
            set {
                this.companyField = value;
                this.RaisePropertyChanged("company");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=2)]
        public string id {
            get {
                return this.idField;
            }
            set {
                this.idField = value;
                this.RaisePropertyChanged("id");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=3)]
        public string date {
            get {
                return this.dateField;
            }
            set {
                this.dateField = value;
                this.RaisePropertyChanged("date");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(Namespace="http://www.amx.com/Service/ConsultTechnician/V1.0", ConfigurationName="TechnicianAppGetResource.ConsultTechnicianInterface")]
    public interface ConsultTechnicianInterface {
        
        // CODEGEN: Generating message contract since the operation GetResource is neither RPC nor document wrapped.
        [System.ServiceModel.OperationContractAttribute(Action="http://www.amx.com/Service/ConsultTechnician/V1.0/GetResource", ReplyAction="*")]
        [System.ServiceModel.FaultContractAttribute(typeof(AmxPeruPSBActivities.TechnicianAppGetResource.ClaroFault), Action="http://www.amx.com/Service/ConsultTechnician/V1.0/GetResource", Name="claroFault", Namespace="http://www.amx.com/CO/Schema/ClaroFault/v1")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        AmxPeruPSBActivities.TechnicianAppGetResource.GetResourceResponse1 GetResource(AmxPeruPSBActivities.TechnicianAppGetResource.GetResourceRequest1 request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://www.amx.com/Service/ConsultTechnician/V1.0/GetResource", ReplyAction="*")]
        System.Threading.Tasks.Task<AmxPeruPSBActivities.TechnicianAppGetResource.GetResourceResponse1> GetResourceAsync(AmxPeruPSBActivities.TechnicianAppGetResource.GetResourceRequest1 request);
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class GetResourceRequest1 {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://www.amx.com/Schema/Operation/GetResource/V1.0", Order=0)]
        public AmxPeruPSBActivities.TechnicianAppGetResource.GetResourceRequest getResourceRequest;
        
        public GetResourceRequest1() {
        }
        
        public GetResourceRequest1(AmxPeruPSBActivities.TechnicianAppGetResource.GetResourceRequest getResourceRequest) {
            this.getResourceRequest = getResourceRequest;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class GetResourceResponse1 {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://www.amx.com/Schema/Operation/GetResource/V1.0", Order=0)]
        public AmxPeruPSBActivities.TechnicianAppGetResource.GetResourceResponse getResourceResponse;
        
        public GetResourceResponse1() {
        }
        
        public GetResourceResponse1(AmxPeruPSBActivities.TechnicianAppGetResource.GetResourceResponse getResourceResponse) {
            this.getResourceResponse = getResourceResponse;
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface ConsultTechnicianInterfaceChannel : AmxPeruPSBActivities.TechnicianAppGetResource.ConsultTechnicianInterface, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class ConsultTechnicianInterfaceClient : System.ServiceModel.ClientBase<AmxPeruPSBActivities.TechnicianAppGetResource.ConsultTechnicianInterface>, AmxPeruPSBActivities.TechnicianAppGetResource.ConsultTechnicianInterface {
        
        public ConsultTechnicianInterfaceClient() {
        }
        
        public ConsultTechnicianInterfaceClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public ConsultTechnicianInterfaceClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public ConsultTechnicianInterfaceClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public ConsultTechnicianInterfaceClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        AmxPeruPSBActivities.TechnicianAppGetResource.GetResourceResponse1 AmxPeruPSBActivities.TechnicianAppGetResource.ConsultTechnicianInterface.GetResource(AmxPeruPSBActivities.TechnicianAppGetResource.GetResourceRequest1 request) {
            return base.Channel.GetResource(request);
        }
        
        public AmxPeruPSBActivities.TechnicianAppGetResource.GetResourceResponse GetResource(AmxPeruPSBActivities.TechnicianAppGetResource.GetResourceRequest getResourceRequest) {
            AmxPeruPSBActivities.TechnicianAppGetResource.GetResourceRequest1 inValue = new AmxPeruPSBActivities.TechnicianAppGetResource.GetResourceRequest1();
            inValue.getResourceRequest = getResourceRequest;
            AmxPeruPSBActivities.TechnicianAppGetResource.GetResourceResponse1 retVal = ((AmxPeruPSBActivities.TechnicianAppGetResource.ConsultTechnicianInterface)(this)).GetResource(inValue);
            return retVal.getResourceResponse;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<AmxPeruPSBActivities.TechnicianAppGetResource.GetResourceResponse1> AmxPeruPSBActivities.TechnicianAppGetResource.ConsultTechnicianInterface.GetResourceAsync(AmxPeruPSBActivities.TechnicianAppGetResource.GetResourceRequest1 request) {
            return base.Channel.GetResourceAsync(request);
        }
        
        public System.Threading.Tasks.Task<AmxPeruPSBActivities.TechnicianAppGetResource.GetResourceResponse1> GetResourceAsync(AmxPeruPSBActivities.TechnicianAppGetResource.GetResourceRequest getResourceRequest) {
            AmxPeruPSBActivities.TechnicianAppGetResource.GetResourceRequest1 inValue = new AmxPeruPSBActivities.TechnicianAppGetResource.GetResourceRequest1();
            inValue.getResourceRequest = getResourceRequest;
            return ((AmxPeruPSBActivities.TechnicianAppGetResource.ConsultTechnicianInterface)(this)).GetResourceAsync(inValue);
        }
    }
}
