//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AmxSoapServicesActivities.ContractsSearchService {
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(Namespace="http://ericsson.com/services/ws_CIL_6", ConfigurationName="ContractsSearchService.ContractsSearchService")]
    public interface ContractsSearchService {
        
        // CODEGEN: Generating message contract since the operation contractsSearch is neither RPC nor document wrapped.
        [System.ServiceModel.OperationContractAttribute(Action="", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        AmxSoapServicesActivities.ContractsSearchService.contractsSearchResponse1 contractsSearch(AmxSoapServicesActivities.ContractsSearchService.contractsSearchRequest1 request);
        
        [System.ServiceModel.OperationContractAttribute(Action="", ReplyAction="*")]
        System.Threading.Tasks.Task<AmxSoapServicesActivities.ContractsSearchService.contractsSearchResponse1> contractsSearchAsync(AmxSoapServicesActivities.ContractsSearchService.contractsSearchRequest1 request);
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.7.2612.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://ericsson.com/services/ws_CIL_6/contractssearch")]
    public partial class contractsSearchRequest : object, System.ComponentModel.INotifyPropertyChanged {
        
        private inputAttributes inputAttributesField;
        
        private sessionChangeRequest sessionChangeRequestField;
        
        /// <remarks/>
        public inputAttributes inputAttributes {
            get {
                return this.inputAttributesField;
            }
            set {
                this.inputAttributesField = value;
                this.RaisePropertyChanged("inputAttributes");
            }
        }
        
        /// <remarks/>
        public sessionChangeRequest sessionChangeRequest {
            get {
                return this.sessionChangeRequestField;
            }
            set {
                this.sessionChangeRequestField = value;
                this.RaisePropertyChanged("sessionChangeRequest");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.7.2612.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://ericsson.com/services/ws_CIL_6/contractssearch")]
    public partial class inputAttributes : object, System.ComponentModel.INotifyPropertyChanged {
        
        private string partyTypeField;
        
        private long contractTypeIdField;
        
        private bool contractTypeIdFieldSpecified;
        
        private long[] typesField;
        
        private bool excludeSubscriberContractsField;
        
        private bool excludeSubscriberContractsFieldSpecified;
        
        private long foreignPlcodeField;
        
        private bool foreignPlcodeFieldSpecified;
        
        private string foreignPlcodePubField;
        
        private long lecCoIdField;
        
        private bool lecCoIdFieldSpecified;
        
        private string lecCoIdPubField;
        
        private bool ignoreBuIndField;
        
        private bool ignoreBuIndFieldSpecified;
        
        private string searcherField;
        
        private string coUserField;
        
        private string coStatusField;
        
        private string csCodeField;
        
        private string csStatusField;
        
        private long csDealeridField;
        
        private bool csDealeridFieldSpecified;
        
        private string csDealeridPubField;
        
        private string smNumField;
        
        private string relatedField;
        
        private string portNumField;
        
        private string devPortNumField;
        
        private long sncodeField;
        
        private bool sncodeFieldSpecified;
        
        private string sncodePubField;
        
        private bool coPofuField;
        
        private bool coPofuFieldSpecified;
        
        private long rpcodeField;
        
        private bool rpcodeFieldSpecified;
        
        private string rpcodePubField;
        
        private string paymentMethodIndField;
        
        private long sccodeField;
        
        private bool sccodeFieldSpecified;
        
        private string sccodePubField;
        
        private string dirnumField;
        
        private string mainDirnumField;
        
        private string billNoField;
        
        private bool useInstallationAddressField;
        
        private bool useInstallationAddressFieldSpecified;
        
        private string adrNameField;
        
        private string adrFnameField;
        
        private string adrLnameField;
        
        private string adrStreetField;
        
        private string adrStreetnoField;
        
        private string adrZipField;
        
        private string adrCityField;
        
        private string adrEmailField;
        
        private System.DateTime adrBirthdtField;
        
        private bool adrBirthdtFieldSpecified;
        
        private string adrSocialsenoField;
        
        private string adrDrivelicenceField;
        
        private string adrPassportnoField;
        
        private string adrCompnoField;
        
        private string adrTaxnoField;
        
        private string adrStateField;
        
        private long countryIdField;
        
        private bool countryIdFieldSpecified;
        
        private string countryIdPubField;
        
        private long submIdField;
        
        private bool submIdFieldSpecified;
        
        private string submIdPubField;
        
        private long plcodeField;
        
        private bool plcodeFieldSpecified;
        
        private string plcodePubField;
        
        private string lowerExtField;
        
        private string upperExtField;
        
        private long srchCountField;
        
        private bool srchCountFieldSpecified;
        
        private string linkedPublicDirnumField;
        
        private long vpnIdField;
        
        private bool vpnIdFieldSpecified;
        
        private string vpnIdPubField;
        
        private bool vpnSubscriberField;
        
        private bool vpnSubscriberFieldSpecified;
        
        private bool externalindField;
        
        private bool externalindFieldSpecified;
        
        private bool laMemberContractField;
        
        private bool laMemberContractFieldSpecified;
        
        private bool flagCaseField;
        
        private bool flagCaseFieldSpecified;
        
        private bool flagMatchcodeField;
        
        private bool flagMatchcodeFieldSpecified;
        
        private string descriptionField;
        
        private long coIdField;
        
        private bool coIdFieldSpecified;
        
        private string coIdPubField;
        
        private long csIdField;
        
        private bool csIdFieldSpecified;
        
        private string csIdPubField;
        
        private long startIndexField;
        
        private bool startIndexFieldSpecified;
        
        private bool nonPendingOnlyField;
        
        private bool nonPendingOnlyFieldSpecified;
        
        private string callDetailField;
        
        private bool markedForReratingField;
        
        private bool markedForReratingFieldSpecified;
        
        private bool bscsContractField;
        
        private bool bscsContractFieldSpecified;
        
        private long familyIdField;
        
        private bool familyIdFieldSpecified;
        
        private string csLevelCodeField;
        
        private bool paymentRespField;
        
        private bool paymentRespFieldSpecified;
        
        private bool csContrRespField;
        
        private bool csContrRespFieldSpecified;
        
        private long rootCsIdField;
        
        private bool rootCsIdFieldSpecified;
        
        private string rootCsIdPubField;
        
        private long fuPackIdField;
        
        private bool fuPackIdFieldSpecified;
        
        private string fuPackIdPubField;
        
        private long fuCoIdField;
        
        private bool fuCoIdFieldSpecified;
        
        private string fuCoIdPubField;
        
        private long fuSncodeField;
        
        private bool fuSncodeFieldSpecified;
        
        private string fuSncodePubField;
        
        private string snStatusField;
        
        private bool notInServiceCriteriaField;
        
        private bool notInServiceCriteriaFieldSpecified;
        
        private long prmIdField;
        
        private bool prmIdFieldSpecified;
        
        private string[] parameterValuesField;
        
        private string salesChannelField;
        
        /// <remarks/>
        public string partyType {
            get {
                return this.partyTypeField;
            }
            set {
                this.partyTypeField = value;
                this.RaisePropertyChanged("partyType");
            }
        }
        
        /// <remarks/>
        public long contractTypeId {
            get {
                return this.contractTypeIdField;
            }
            set {
                this.contractTypeIdField = value;
                this.RaisePropertyChanged("contractTypeId");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool contractTypeIdSpecified {
            get {
                return this.contractTypeIdFieldSpecified;
            }
            set {
                this.contractTypeIdFieldSpecified = value;
                this.RaisePropertyChanged("contractTypeIdSpecified");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlArrayItemAttribute("contractTypeId", IsNullable=false)]
        public long[] types {
            get {
                return this.typesField;
            }
            set {
                this.typesField = value;
                this.RaisePropertyChanged("types");
            }
        }
        
        /// <remarks/>
        public bool excludeSubscriberContracts {
            get {
                return this.excludeSubscriberContractsField;
            }
            set {
                this.excludeSubscriberContractsField = value;
                this.RaisePropertyChanged("excludeSubscriberContracts");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool excludeSubscriberContractsSpecified {
            get {
                return this.excludeSubscriberContractsFieldSpecified;
            }
            set {
                this.excludeSubscriberContractsFieldSpecified = value;
                this.RaisePropertyChanged("excludeSubscriberContractsSpecified");
            }
        }
        
        /// <remarks/>
        public long foreignPlcode {
            get {
                return this.foreignPlcodeField;
            }
            set {
                this.foreignPlcodeField = value;
                this.RaisePropertyChanged("foreignPlcode");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool foreignPlcodeSpecified {
            get {
                return this.foreignPlcodeFieldSpecified;
            }
            set {
                this.foreignPlcodeFieldSpecified = value;
                this.RaisePropertyChanged("foreignPlcodeSpecified");
            }
        }
        
        /// <remarks/>
        public string foreignPlcodePub {
            get {
                return this.foreignPlcodePubField;
            }
            set {
                this.foreignPlcodePubField = value;
                this.RaisePropertyChanged("foreignPlcodePub");
            }
        }
        
        /// <remarks/>
        public long lecCoId {
            get {
                return this.lecCoIdField;
            }
            set {
                this.lecCoIdField = value;
                this.RaisePropertyChanged("lecCoId");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool lecCoIdSpecified {
            get {
                return this.lecCoIdFieldSpecified;
            }
            set {
                this.lecCoIdFieldSpecified = value;
                this.RaisePropertyChanged("lecCoIdSpecified");
            }
        }
        
        /// <remarks/>
        public string lecCoIdPub {
            get {
                return this.lecCoIdPubField;
            }
            set {
                this.lecCoIdPubField = value;
                this.RaisePropertyChanged("lecCoIdPub");
            }
        }
        
        /// <remarks/>
        public bool ignoreBuInd {
            get {
                return this.ignoreBuIndField;
            }
            set {
                this.ignoreBuIndField = value;
                this.RaisePropertyChanged("ignoreBuInd");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool ignoreBuIndSpecified {
            get {
                return this.ignoreBuIndFieldSpecified;
            }
            set {
                this.ignoreBuIndFieldSpecified = value;
                this.RaisePropertyChanged("ignoreBuIndSpecified");
            }
        }
        
        /// <remarks/>
        public string searcher {
            get {
                return this.searcherField;
            }
            set {
                this.searcherField = value;
                this.RaisePropertyChanged("searcher");
            }
        }
        
        /// <remarks/>
        public string coUser {
            get {
                return this.coUserField;
            }
            set {
                this.coUserField = value;
                this.RaisePropertyChanged("coUser");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(DataType="integer")]
        public string coStatus {
            get {
                return this.coStatusField;
            }
            set {
                this.coStatusField = value;
                this.RaisePropertyChanged("coStatus");
            }
        }
        
        /// <remarks/>
        public string csCode {
            get {
                return this.csCodeField;
            }
            set {
                this.csCodeField = value;
                this.RaisePropertyChanged("csCode");
            }
        }
        
        /// <remarks/>
        public string csStatus {
            get {
                return this.csStatusField;
            }
            set {
                this.csStatusField = value;
                this.RaisePropertyChanged("csStatus");
            }
        }
        
        /// <remarks/>
        public long csDealerid {
            get {
                return this.csDealeridField;
            }
            set {
                this.csDealeridField = value;
                this.RaisePropertyChanged("csDealerid");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool csDealeridSpecified {
            get {
                return this.csDealeridFieldSpecified;
            }
            set {
                this.csDealeridFieldSpecified = value;
                this.RaisePropertyChanged("csDealeridSpecified");
            }
        }
        
        /// <remarks/>
        public string csDealeridPub {
            get {
                return this.csDealeridPubField;
            }
            set {
                this.csDealeridPubField = value;
                this.RaisePropertyChanged("csDealeridPub");
            }
        }
        
        /// <remarks/>
        public string smNum {
            get {
                return this.smNumField;
            }
            set {
                this.smNumField = value;
                this.RaisePropertyChanged("smNum");
            }
        }
        
        /// <remarks/>
        public string related {
            get {
                return this.relatedField;
            }
            set {
                this.relatedField = value;
                this.RaisePropertyChanged("related");
            }
        }
        
        /// <remarks/>
        public string portNum {
            get {
                return this.portNumField;
            }
            set {
                this.portNumField = value;
                this.RaisePropertyChanged("portNum");
            }
        }
        
        /// <remarks/>
        public string devPortNum {
            get {
                return this.devPortNumField;
            }
            set {
                this.devPortNumField = value;
                this.RaisePropertyChanged("devPortNum");
            }
        }
        
        /// <remarks/>
        public long sncode {
            get {
                return this.sncodeField;
            }
            set {
                this.sncodeField = value;
                this.RaisePropertyChanged("sncode");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool sncodeSpecified {
            get {
                return this.sncodeFieldSpecified;
            }
            set {
                this.sncodeFieldSpecified = value;
                this.RaisePropertyChanged("sncodeSpecified");
            }
        }
        
        /// <remarks/>
        public string sncodePub {
            get {
                return this.sncodePubField;
            }
            set {
                this.sncodePubField = value;
                this.RaisePropertyChanged("sncodePub");
            }
        }
        
        /// <remarks/>
        public bool coPofu {
            get {
                return this.coPofuField;
            }
            set {
                this.coPofuField = value;
                this.RaisePropertyChanged("coPofu");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool coPofuSpecified {
            get {
                return this.coPofuFieldSpecified;
            }
            set {
                this.coPofuFieldSpecified = value;
                this.RaisePropertyChanged("coPofuSpecified");
            }
        }
        
        /// <remarks/>
        public long rpcode {
            get {
                return this.rpcodeField;
            }
            set {
                this.rpcodeField = value;
                this.RaisePropertyChanged("rpcode");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool rpcodeSpecified {
            get {
                return this.rpcodeFieldSpecified;
            }
            set {
                this.rpcodeFieldSpecified = value;
                this.RaisePropertyChanged("rpcodeSpecified");
            }
        }
        
        /// <remarks/>
        public string rpcodePub {
            get {
                return this.rpcodePubField;
            }
            set {
                this.rpcodePubField = value;
                this.RaisePropertyChanged("rpcodePub");
            }
        }
        
        /// <remarks/>
        public string paymentMethodInd {
            get {
                return this.paymentMethodIndField;
            }
            set {
                this.paymentMethodIndField = value;
                this.RaisePropertyChanged("paymentMethodInd");
            }
        }
        
        /// <remarks/>
        public long sccode {
            get {
                return this.sccodeField;
            }
            set {
                this.sccodeField = value;
                this.RaisePropertyChanged("sccode");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool sccodeSpecified {
            get {
                return this.sccodeFieldSpecified;
            }
            set {
                this.sccodeFieldSpecified = value;
                this.RaisePropertyChanged("sccodeSpecified");
            }
        }
        
        /// <remarks/>
        public string sccodePub {
            get {
                return this.sccodePubField;
            }
            set {
                this.sccodePubField = value;
                this.RaisePropertyChanged("sccodePub");
            }
        }
        
        /// <remarks/>
        public string dirnum {
            get {
                return this.dirnumField;
            }
            set {
                this.dirnumField = value;
                this.RaisePropertyChanged("dirnum");
            }
        }
        
        /// <remarks/>
        public string mainDirnum {
            get {
                return this.mainDirnumField;
            }
            set {
                this.mainDirnumField = value;
                this.RaisePropertyChanged("mainDirnum");
            }
        }
        
        /// <remarks/>
        public string billNo {
            get {
                return this.billNoField;
            }
            set {
                this.billNoField = value;
                this.RaisePropertyChanged("billNo");
            }
        }
        
        /// <remarks/>
        public bool useInstallationAddress {
            get {
                return this.useInstallationAddressField;
            }
            set {
                this.useInstallationAddressField = value;
                this.RaisePropertyChanged("useInstallationAddress");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool useInstallationAddressSpecified {
            get {
                return this.useInstallationAddressFieldSpecified;
            }
            set {
                this.useInstallationAddressFieldSpecified = value;
                this.RaisePropertyChanged("useInstallationAddressSpecified");
            }
        }
        
        /// <remarks/>
        public string adrName {
            get {
                return this.adrNameField;
            }
            set {
                this.adrNameField = value;
                this.RaisePropertyChanged("adrName");
            }
        }
        
        /// <remarks/>
        public string adrFname {
            get {
                return this.adrFnameField;
            }
            set {
                this.adrFnameField = value;
                this.RaisePropertyChanged("adrFname");
            }
        }
        
        /// <remarks/>
        public string adrLname {
            get {
                return this.adrLnameField;
            }
            set {
                this.adrLnameField = value;
                this.RaisePropertyChanged("adrLname");
            }
        }
        
        /// <remarks/>
        public string adrStreet {
            get {
                return this.adrStreetField;
            }
            set {
                this.adrStreetField = value;
                this.RaisePropertyChanged("adrStreet");
            }
        }
        
        /// <remarks/>
        public string adrStreetno {
            get {
                return this.adrStreetnoField;
            }
            set {
                this.adrStreetnoField = value;
                this.RaisePropertyChanged("adrStreetno");
            }
        }
        
        /// <remarks/>
        public string adrZip {
            get {
                return this.adrZipField;
            }
            set {
                this.adrZipField = value;
                this.RaisePropertyChanged("adrZip");
            }
        }
        
        /// <remarks/>
        public string adrCity {
            get {
                return this.adrCityField;
            }
            set {
                this.adrCityField = value;
                this.RaisePropertyChanged("adrCity");
            }
        }
        
        /// <remarks/>
        public string adrEmail {
            get {
                return this.adrEmailField;
            }
            set {
                this.adrEmailField = value;
                this.RaisePropertyChanged("adrEmail");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(DataType="date")]
        public System.DateTime adrBirthdt {
            get {
                return this.adrBirthdtField;
            }
            set {
                this.adrBirthdtField = value;
                this.RaisePropertyChanged("adrBirthdt");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool adrBirthdtSpecified {
            get {
                return this.adrBirthdtFieldSpecified;
            }
            set {
                this.adrBirthdtFieldSpecified = value;
                this.RaisePropertyChanged("adrBirthdtSpecified");
            }
        }
        
        /// <remarks/>
        public string adrSocialseno {
            get {
                return this.adrSocialsenoField;
            }
            set {
                this.adrSocialsenoField = value;
                this.RaisePropertyChanged("adrSocialseno");
            }
        }
        
        /// <remarks/>
        public string adrDrivelicence {
            get {
                return this.adrDrivelicenceField;
            }
            set {
                this.adrDrivelicenceField = value;
                this.RaisePropertyChanged("adrDrivelicence");
            }
        }
        
        /// <remarks/>
        public string adrPassportno {
            get {
                return this.adrPassportnoField;
            }
            set {
                this.adrPassportnoField = value;
                this.RaisePropertyChanged("adrPassportno");
            }
        }
        
        /// <remarks/>
        public string adrCompno {
            get {
                return this.adrCompnoField;
            }
            set {
                this.adrCompnoField = value;
                this.RaisePropertyChanged("adrCompno");
            }
        }
        
        /// <remarks/>
        public string adrTaxno {
            get {
                return this.adrTaxnoField;
            }
            set {
                this.adrTaxnoField = value;
                this.RaisePropertyChanged("adrTaxno");
            }
        }
        
        /// <remarks/>
        public string adrState {
            get {
                return this.adrStateField;
            }
            set {
                this.adrStateField = value;
                this.RaisePropertyChanged("adrState");
            }
        }
        
        /// <remarks/>
        public long countryId {
            get {
                return this.countryIdField;
            }
            set {
                this.countryIdField = value;
                this.RaisePropertyChanged("countryId");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool countryIdSpecified {
            get {
                return this.countryIdFieldSpecified;
            }
            set {
                this.countryIdFieldSpecified = value;
                this.RaisePropertyChanged("countryIdSpecified");
            }
        }
        
        /// <remarks/>
        public string countryIdPub {
            get {
                return this.countryIdPubField;
            }
            set {
                this.countryIdPubField = value;
                this.RaisePropertyChanged("countryIdPub");
            }
        }
        
        /// <remarks/>
        public long submId {
            get {
                return this.submIdField;
            }
            set {
                this.submIdField = value;
                this.RaisePropertyChanged("submId");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool submIdSpecified {
            get {
                return this.submIdFieldSpecified;
            }
            set {
                this.submIdFieldSpecified = value;
                this.RaisePropertyChanged("submIdSpecified");
            }
        }
        
        /// <remarks/>
        public string submIdPub {
            get {
                return this.submIdPubField;
            }
            set {
                this.submIdPubField = value;
                this.RaisePropertyChanged("submIdPub");
            }
        }
        
        /// <remarks/>
        public long plcode {
            get {
                return this.plcodeField;
            }
            set {
                this.plcodeField = value;
                this.RaisePropertyChanged("plcode");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool plcodeSpecified {
            get {
                return this.plcodeFieldSpecified;
            }
            set {
                this.plcodeFieldSpecified = value;
                this.RaisePropertyChanged("plcodeSpecified");
            }
        }
        
        /// <remarks/>
        public string plcodePub {
            get {
                return this.plcodePubField;
            }
            set {
                this.plcodePubField = value;
                this.RaisePropertyChanged("plcodePub");
            }
        }
        
        /// <remarks/>
        public string lowerExt {
            get {
                return this.lowerExtField;
            }
            set {
                this.lowerExtField = value;
                this.RaisePropertyChanged("lowerExt");
            }
        }
        
        /// <remarks/>
        public string upperExt {
            get {
                return this.upperExtField;
            }
            set {
                this.upperExtField = value;
                this.RaisePropertyChanged("upperExt");
            }
        }
        
        /// <remarks/>
        public long srchCount {
            get {
                return this.srchCountField;
            }
            set {
                this.srchCountField = value;
                this.RaisePropertyChanged("srchCount");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool srchCountSpecified {
            get {
                return this.srchCountFieldSpecified;
            }
            set {
                this.srchCountFieldSpecified = value;
                this.RaisePropertyChanged("srchCountSpecified");
            }
        }
        
        /// <remarks/>
        public string linkedPublicDirnum {
            get {
                return this.linkedPublicDirnumField;
            }
            set {
                this.linkedPublicDirnumField = value;
                this.RaisePropertyChanged("linkedPublicDirnum");
            }
        }
        
        /// <remarks/>
        public long vpnId {
            get {
                return this.vpnIdField;
            }
            set {
                this.vpnIdField = value;
                this.RaisePropertyChanged("vpnId");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool vpnIdSpecified {
            get {
                return this.vpnIdFieldSpecified;
            }
            set {
                this.vpnIdFieldSpecified = value;
                this.RaisePropertyChanged("vpnIdSpecified");
            }
        }
        
        /// <remarks/>
        public string vpnIdPub {
            get {
                return this.vpnIdPubField;
            }
            set {
                this.vpnIdPubField = value;
                this.RaisePropertyChanged("vpnIdPub");
            }
        }
        
        /// <remarks/>
        public bool vpnSubscriber {
            get {
                return this.vpnSubscriberField;
            }
            set {
                this.vpnSubscriberField = value;
                this.RaisePropertyChanged("vpnSubscriber");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool vpnSubscriberSpecified {
            get {
                return this.vpnSubscriberFieldSpecified;
            }
            set {
                this.vpnSubscriberFieldSpecified = value;
                this.RaisePropertyChanged("vpnSubscriberSpecified");
            }
        }
        
        /// <remarks/>
        public bool externalind {
            get {
                return this.externalindField;
            }
            set {
                this.externalindField = value;
                this.RaisePropertyChanged("externalind");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool externalindSpecified {
            get {
                return this.externalindFieldSpecified;
            }
            set {
                this.externalindFieldSpecified = value;
                this.RaisePropertyChanged("externalindSpecified");
            }
        }
        
        /// <remarks/>
        public bool laMemberContract {
            get {
                return this.laMemberContractField;
            }
            set {
                this.laMemberContractField = value;
                this.RaisePropertyChanged("laMemberContract");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool laMemberContractSpecified {
            get {
                return this.laMemberContractFieldSpecified;
            }
            set {
                this.laMemberContractFieldSpecified = value;
                this.RaisePropertyChanged("laMemberContractSpecified");
            }
        }
        
        /// <remarks/>
        public bool flagCase {
            get {
                return this.flagCaseField;
            }
            set {
                this.flagCaseField = value;
                this.RaisePropertyChanged("flagCase");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool flagCaseSpecified {
            get {
                return this.flagCaseFieldSpecified;
            }
            set {
                this.flagCaseFieldSpecified = value;
                this.RaisePropertyChanged("flagCaseSpecified");
            }
        }
        
        /// <remarks/>
        public bool flagMatchcode {
            get {
                return this.flagMatchcodeField;
            }
            set {
                this.flagMatchcodeField = value;
                this.RaisePropertyChanged("flagMatchcode");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool flagMatchcodeSpecified {
            get {
                return this.flagMatchcodeFieldSpecified;
            }
            set {
                this.flagMatchcodeFieldSpecified = value;
                this.RaisePropertyChanged("flagMatchcodeSpecified");
            }
        }
        
        /// <remarks/>
        public string description {
            get {
                return this.descriptionField;
            }
            set {
                this.descriptionField = value;
                this.RaisePropertyChanged("description");
            }
        }
        
        /// <remarks/>
        public long coId {
            get {
                return this.coIdField;
            }
            set {
                this.coIdField = value;
                this.RaisePropertyChanged("coId");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool coIdSpecified {
            get {
                return this.coIdFieldSpecified;
            }
            set {
                this.coIdFieldSpecified = value;
                this.RaisePropertyChanged("coIdSpecified");
            }
        }
        
        /// <remarks/>
        public string coIdPub {
            get {
                return this.coIdPubField;
            }
            set {
                this.coIdPubField = value;
                this.RaisePropertyChanged("coIdPub");
            }
        }
        
        /// <remarks/>
        public long csId {
            get {
                return this.csIdField;
            }
            set {
                this.csIdField = value;
                this.RaisePropertyChanged("csId");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool csIdSpecified {
            get {
                return this.csIdFieldSpecified;
            }
            set {
                this.csIdFieldSpecified = value;
                this.RaisePropertyChanged("csIdSpecified");
            }
        }
        
        /// <remarks/>
        public string csIdPub {
            get {
                return this.csIdPubField;
            }
            set {
                this.csIdPubField = value;
                this.RaisePropertyChanged("csIdPub");
            }
        }
        
        /// <remarks/>
        public long startIndex {
            get {
                return this.startIndexField;
            }
            set {
                this.startIndexField = value;
                this.RaisePropertyChanged("startIndex");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool startIndexSpecified {
            get {
                return this.startIndexFieldSpecified;
            }
            set {
                this.startIndexFieldSpecified = value;
                this.RaisePropertyChanged("startIndexSpecified");
            }
        }
        
        /// <remarks/>
        public bool nonPendingOnly {
            get {
                return this.nonPendingOnlyField;
            }
            set {
                this.nonPendingOnlyField = value;
                this.RaisePropertyChanged("nonPendingOnly");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool nonPendingOnlySpecified {
            get {
                return this.nonPendingOnlyFieldSpecified;
            }
            set {
                this.nonPendingOnlyFieldSpecified = value;
                this.RaisePropertyChanged("nonPendingOnlySpecified");
            }
        }
        
        /// <remarks/>
        public string callDetail {
            get {
                return this.callDetailField;
            }
            set {
                this.callDetailField = value;
                this.RaisePropertyChanged("callDetail");
            }
        }
        
        /// <remarks/>
        public bool markedForRerating {
            get {
                return this.markedForReratingField;
            }
            set {
                this.markedForReratingField = value;
                this.RaisePropertyChanged("markedForRerating");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool markedForReratingSpecified {
            get {
                return this.markedForReratingFieldSpecified;
            }
            set {
                this.markedForReratingFieldSpecified = value;
                this.RaisePropertyChanged("markedForReratingSpecified");
            }
        }
        
        /// <remarks/>
        public bool bscsContract {
            get {
                return this.bscsContractField;
            }
            set {
                this.bscsContractField = value;
                this.RaisePropertyChanged("bscsContract");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool bscsContractSpecified {
            get {
                return this.bscsContractFieldSpecified;
            }
            set {
                this.bscsContractFieldSpecified = value;
                this.RaisePropertyChanged("bscsContractSpecified");
            }
        }
        
        /// <remarks/>
        public long familyId {
            get {
                return this.familyIdField;
            }
            set {
                this.familyIdField = value;
                this.RaisePropertyChanged("familyId");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool familyIdSpecified {
            get {
                return this.familyIdFieldSpecified;
            }
            set {
                this.familyIdFieldSpecified = value;
                this.RaisePropertyChanged("familyIdSpecified");
            }
        }
        
        /// <remarks/>
        public string csLevelCode {
            get {
                return this.csLevelCodeField;
            }
            set {
                this.csLevelCodeField = value;
                this.RaisePropertyChanged("csLevelCode");
            }
        }
        
        /// <remarks/>
        public bool paymentResp {
            get {
                return this.paymentRespField;
            }
            set {
                this.paymentRespField = value;
                this.RaisePropertyChanged("paymentResp");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool paymentRespSpecified {
            get {
                return this.paymentRespFieldSpecified;
            }
            set {
                this.paymentRespFieldSpecified = value;
                this.RaisePropertyChanged("paymentRespSpecified");
            }
        }
        
        /// <remarks/>
        public bool csContrResp {
            get {
                return this.csContrRespField;
            }
            set {
                this.csContrRespField = value;
                this.RaisePropertyChanged("csContrResp");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool csContrRespSpecified {
            get {
                return this.csContrRespFieldSpecified;
            }
            set {
                this.csContrRespFieldSpecified = value;
                this.RaisePropertyChanged("csContrRespSpecified");
            }
        }
        
        /// <remarks/>
        public long rootCsId {
            get {
                return this.rootCsIdField;
            }
            set {
                this.rootCsIdField = value;
                this.RaisePropertyChanged("rootCsId");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool rootCsIdSpecified {
            get {
                return this.rootCsIdFieldSpecified;
            }
            set {
                this.rootCsIdFieldSpecified = value;
                this.RaisePropertyChanged("rootCsIdSpecified");
            }
        }
        
        /// <remarks/>
        public string rootCsIdPub {
            get {
                return this.rootCsIdPubField;
            }
            set {
                this.rootCsIdPubField = value;
                this.RaisePropertyChanged("rootCsIdPub");
            }
        }
        
        /// <remarks/>
        public long fuPackId {
            get {
                return this.fuPackIdField;
            }
            set {
                this.fuPackIdField = value;
                this.RaisePropertyChanged("fuPackId");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool fuPackIdSpecified {
            get {
                return this.fuPackIdFieldSpecified;
            }
            set {
                this.fuPackIdFieldSpecified = value;
                this.RaisePropertyChanged("fuPackIdSpecified");
            }
        }
        
        /// <remarks/>
        public string fuPackIdPub {
            get {
                return this.fuPackIdPubField;
            }
            set {
                this.fuPackIdPubField = value;
                this.RaisePropertyChanged("fuPackIdPub");
            }
        }
        
        /// <remarks/>
        public long fuCoId {
            get {
                return this.fuCoIdField;
            }
            set {
                this.fuCoIdField = value;
                this.RaisePropertyChanged("fuCoId");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool fuCoIdSpecified {
            get {
                return this.fuCoIdFieldSpecified;
            }
            set {
                this.fuCoIdFieldSpecified = value;
                this.RaisePropertyChanged("fuCoIdSpecified");
            }
        }
        
        /// <remarks/>
        public string fuCoIdPub {
            get {
                return this.fuCoIdPubField;
            }
            set {
                this.fuCoIdPubField = value;
                this.RaisePropertyChanged("fuCoIdPub");
            }
        }
        
        /// <remarks/>
        public long fuSncode {
            get {
                return this.fuSncodeField;
            }
            set {
                this.fuSncodeField = value;
                this.RaisePropertyChanged("fuSncode");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool fuSncodeSpecified {
            get {
                return this.fuSncodeFieldSpecified;
            }
            set {
                this.fuSncodeFieldSpecified = value;
                this.RaisePropertyChanged("fuSncodeSpecified");
            }
        }
        
        /// <remarks/>
        public string fuSncodePub {
            get {
                return this.fuSncodePubField;
            }
            set {
                this.fuSncodePubField = value;
                this.RaisePropertyChanged("fuSncodePub");
            }
        }
        
        /// <remarks/>
        public string snStatus {
            get {
                return this.snStatusField;
            }
            set {
                this.snStatusField = value;
                this.RaisePropertyChanged("snStatus");
            }
        }
        
        /// <remarks/>
        public bool notInServiceCriteria {
            get {
                return this.notInServiceCriteriaField;
            }
            set {
                this.notInServiceCriteriaField = value;
                this.RaisePropertyChanged("notInServiceCriteria");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool notInServiceCriteriaSpecified {
            get {
                return this.notInServiceCriteriaFieldSpecified;
            }
            set {
                this.notInServiceCriteriaFieldSpecified = value;
                this.RaisePropertyChanged("notInServiceCriteriaSpecified");
            }
        }
        
        /// <remarks/>
        public long prmId {
            get {
                return this.prmIdField;
            }
            set {
                this.prmIdField = value;
                this.RaisePropertyChanged("prmId");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool prmIdSpecified {
            get {
                return this.prmIdFieldSpecified;
            }
            set {
                this.prmIdFieldSpecified = value;
                this.RaisePropertyChanged("prmIdSpecified");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlArrayItemAttribute("value", IsNullable=false)]
        public string[] parameterValues {
            get {
                return this.parameterValuesField;
            }
            set {
                this.parameterValuesField = value;
                this.RaisePropertyChanged("parameterValues");
            }
        }
        
        /// <remarks/>
        public string salesChannel {
            get {
                return this.salesChannelField;
            }
            set {
                this.salesChannelField = value;
                this.RaisePropertyChanged("salesChannel");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.7.2612.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://ericsson.com/services/ws_CIL_6/contractssearch")]
    public partial class dirnumBlocksListpartResponse : object, System.ComponentModel.INotifyPropertyChanged {
        
        private string lowerExtField;
        
        private string upperExtField;
        
        /// <remarks/>
        public string lowerExt {
            get {
                return this.lowerExtField;
            }
            set {
                this.lowerExtField = value;
                this.RaisePropertyChanged("lowerExt");
            }
        }
        
        /// <remarks/>
        public string upperExt {
            get {
                return this.upperExtField;
            }
            set {
                this.upperExtField = value;
                this.RaisePropertyChanged("upperExt");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.7.2612.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://ericsson.com/services/ws_CIL_6/contractssearch")]
    public partial class contractsListpartResponse : object, System.ComponentModel.INotifyPropertyChanged {
        
        private long contractTypeIdField;
        
        private bool contractTypeIdFieldSpecified;
        
        private long foreignPlcodeField;
        
        private bool foreignPlcodeFieldSpecified;
        
        private long homeBidGroupIdField;
        
        private bool homeBidGroupIdFieldSpecified;
        
        private long foreignBidGroupIdField;
        
        private bool foreignBidGroupIdFieldSpecified;
        
        private long lecCoIdField;
        
        private bool lecCoIdFieldSpecified;
        
        private string lecCoIdPubField;
        
        private long buIdField;
        
        private bool buIdFieldSpecified;
        
        private string coStatusField;
        
        private string csCodeField;
        
        private string dirnumField;
        
        private dirnumBlocksListpartResponse[] dirnumBlocksField;
        
        private string adrFnameField;
        
        private string adrLnameField;
        
        private string adrNameField;
        
        private string adrStreetField;
        
        private string adrStreetnoField;
        
        private string adrZipField;
        
        private string adrCityField;
        
        private long submIdField;
        
        private bool submIdFieldSpecified;
        
        private long plcodeField;
        
        private bool plcodeFieldSpecified;
        
        private string coTypeField;
        
        private long vpnIdField;
        
        private bool vpnIdFieldSpecified;
        
        private bool externalindField;
        
        private bool externalindFieldSpecified;
        
        private long rpcodeField;
        
        private bool rpcodeFieldSpecified;
        
        private System.DateTime coActivatedField;
        
        private bool coActivatedFieldSpecified;
        
        private string portNumField;
        
        private string smNumField;
        
        private string devPortNumField;
        
        private long hlcodeField;
        
        private bool hlcodeFieldSpecified;
        
        private long coIdField;
        
        private bool coIdFieldSpecified;
        
        private string coIdPubField;
        
        private long mainCoIdField;
        
        private bool mainCoIdFieldSpecified;
        
        private string mainCoIdPubField;
        
        private long csIdField;
        
        private bool csIdFieldSpecified;
        
        private string csIdPubField;
        
        private string descriptionField;
        
        private bool currentDnField;
        
        private bool currentDnFieldSpecified;
        
        private bool dnPendingField;
        
        private bool dnPendingFieldSpecified;
        
        private bool markedForReratingField;
        
        private bool markedForReratingFieldSpecified;
        
        private long csDealeridField;
        
        private bool csDealeridFieldSpecified;
        
        private string paymentRespField;
        
        private string csContrRespField;
        
        private string paymentMethodIndField;
        
        private long coTemplateIdField;
        
        private bool coTemplateIdFieldSpecified;
        
        private string coTemplateIdPubField;
        
        private string[] salesChannelsField;
        
        /// <remarks/>
        public long contractTypeId {
            get {
                return this.contractTypeIdField;
            }
            set {
                this.contractTypeIdField = value;
                this.RaisePropertyChanged("contractTypeId");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool contractTypeIdSpecified {
            get {
                return this.contractTypeIdFieldSpecified;
            }
            set {
                this.contractTypeIdFieldSpecified = value;
                this.RaisePropertyChanged("contractTypeIdSpecified");
            }
        }
        
        /// <remarks/>
        public long foreignPlcode {
            get {
                return this.foreignPlcodeField;
            }
            set {
                this.foreignPlcodeField = value;
                this.RaisePropertyChanged("foreignPlcode");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool foreignPlcodeSpecified {
            get {
                return this.foreignPlcodeFieldSpecified;
            }
            set {
                this.foreignPlcodeFieldSpecified = value;
                this.RaisePropertyChanged("foreignPlcodeSpecified");
            }
        }
        
        /// <remarks/>
        public long homeBidGroupId {
            get {
                return this.homeBidGroupIdField;
            }
            set {
                this.homeBidGroupIdField = value;
                this.RaisePropertyChanged("homeBidGroupId");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool homeBidGroupIdSpecified {
            get {
                return this.homeBidGroupIdFieldSpecified;
            }
            set {
                this.homeBidGroupIdFieldSpecified = value;
                this.RaisePropertyChanged("homeBidGroupIdSpecified");
            }
        }
        
        /// <remarks/>
        public long foreignBidGroupId {
            get {
                return this.foreignBidGroupIdField;
            }
            set {
                this.foreignBidGroupIdField = value;
                this.RaisePropertyChanged("foreignBidGroupId");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool foreignBidGroupIdSpecified {
            get {
                return this.foreignBidGroupIdFieldSpecified;
            }
            set {
                this.foreignBidGroupIdFieldSpecified = value;
                this.RaisePropertyChanged("foreignBidGroupIdSpecified");
            }
        }
        
        /// <remarks/>
        public long lecCoId {
            get {
                return this.lecCoIdField;
            }
            set {
                this.lecCoIdField = value;
                this.RaisePropertyChanged("lecCoId");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool lecCoIdSpecified {
            get {
                return this.lecCoIdFieldSpecified;
            }
            set {
                this.lecCoIdFieldSpecified = value;
                this.RaisePropertyChanged("lecCoIdSpecified");
            }
        }
        
        /// <remarks/>
        public string lecCoIdPub {
            get {
                return this.lecCoIdPubField;
            }
            set {
                this.lecCoIdPubField = value;
                this.RaisePropertyChanged("lecCoIdPub");
            }
        }
        
        /// <remarks/>
        public long buId {
            get {
                return this.buIdField;
            }
            set {
                this.buIdField = value;
                this.RaisePropertyChanged("buId");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool buIdSpecified {
            get {
                return this.buIdFieldSpecified;
            }
            set {
                this.buIdFieldSpecified = value;
                this.RaisePropertyChanged("buIdSpecified");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(DataType="integer")]
        public string coStatus {
            get {
                return this.coStatusField;
            }
            set {
                this.coStatusField = value;
                this.RaisePropertyChanged("coStatus");
            }
        }
        
        /// <remarks/>
        public string csCode {
            get {
                return this.csCodeField;
            }
            set {
                this.csCodeField = value;
                this.RaisePropertyChanged("csCode");
            }
        }
        
        /// <remarks/>
        public string dirnum {
            get {
                return this.dirnumField;
            }
            set {
                this.dirnumField = value;
                this.RaisePropertyChanged("dirnum");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlArrayItemAttribute("item", IsNullable=false)]
        public dirnumBlocksListpartResponse[] dirnumBlocks {
            get {
                return this.dirnumBlocksField;
            }
            set {
                this.dirnumBlocksField = value;
                this.RaisePropertyChanged("dirnumBlocks");
            }
        }
        
        /// <remarks/>
        public string adrFname {
            get {
                return this.adrFnameField;
            }
            set {
                this.adrFnameField = value;
                this.RaisePropertyChanged("adrFname");
            }
        }
        
        /// <remarks/>
        public string adrLname {
            get {
                return this.adrLnameField;
            }
            set {
                this.adrLnameField = value;
                this.RaisePropertyChanged("adrLname");
            }
        }
        
        /// <remarks/>
        public string adrName {
            get {
                return this.adrNameField;
            }
            set {
                this.adrNameField = value;
                this.RaisePropertyChanged("adrName");
            }
        }
        
        /// <remarks/>
        public string adrStreet {
            get {
                return this.adrStreetField;
            }
            set {
                this.adrStreetField = value;
                this.RaisePropertyChanged("adrStreet");
            }
        }
        
        /// <remarks/>
        public string adrStreetno {
            get {
                return this.adrStreetnoField;
            }
            set {
                this.adrStreetnoField = value;
                this.RaisePropertyChanged("adrStreetno");
            }
        }
        
        /// <remarks/>
        public string adrZip {
            get {
                return this.adrZipField;
            }
            set {
                this.adrZipField = value;
                this.RaisePropertyChanged("adrZip");
            }
        }
        
        /// <remarks/>
        public string adrCity {
            get {
                return this.adrCityField;
            }
            set {
                this.adrCityField = value;
                this.RaisePropertyChanged("adrCity");
            }
        }
        
        /// <remarks/>
        public long submId {
            get {
                return this.submIdField;
            }
            set {
                this.submIdField = value;
                this.RaisePropertyChanged("submId");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool submIdSpecified {
            get {
                return this.submIdFieldSpecified;
            }
            set {
                this.submIdFieldSpecified = value;
                this.RaisePropertyChanged("submIdSpecified");
            }
        }
        
        /// <remarks/>
        public long plcode {
            get {
                return this.plcodeField;
            }
            set {
                this.plcodeField = value;
                this.RaisePropertyChanged("plcode");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool plcodeSpecified {
            get {
                return this.plcodeFieldSpecified;
            }
            set {
                this.plcodeFieldSpecified = value;
                this.RaisePropertyChanged("plcodeSpecified");
            }
        }
        
        /// <remarks/>
        public string coType {
            get {
                return this.coTypeField;
            }
            set {
                this.coTypeField = value;
                this.RaisePropertyChanged("coType");
            }
        }
        
        /// <remarks/>
        public long vpnId {
            get {
                return this.vpnIdField;
            }
            set {
                this.vpnIdField = value;
                this.RaisePropertyChanged("vpnId");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool vpnIdSpecified {
            get {
                return this.vpnIdFieldSpecified;
            }
            set {
                this.vpnIdFieldSpecified = value;
                this.RaisePropertyChanged("vpnIdSpecified");
            }
        }
        
        /// <remarks/>
        public bool externalind {
            get {
                return this.externalindField;
            }
            set {
                this.externalindField = value;
                this.RaisePropertyChanged("externalind");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool externalindSpecified {
            get {
                return this.externalindFieldSpecified;
            }
            set {
                this.externalindFieldSpecified = value;
                this.RaisePropertyChanged("externalindSpecified");
            }
        }
        
        /// <remarks/>
        public long rpcode {
            get {
                return this.rpcodeField;
            }
            set {
                this.rpcodeField = value;
                this.RaisePropertyChanged("rpcode");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool rpcodeSpecified {
            get {
                return this.rpcodeFieldSpecified;
            }
            set {
                this.rpcodeFieldSpecified = value;
                this.RaisePropertyChanged("rpcodeSpecified");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(DataType="date")]
        public System.DateTime coActivated {
            get {
                return this.coActivatedField;
            }
            set {
                this.coActivatedField = value;
                this.RaisePropertyChanged("coActivated");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool coActivatedSpecified {
            get {
                return this.coActivatedFieldSpecified;
            }
            set {
                this.coActivatedFieldSpecified = value;
                this.RaisePropertyChanged("coActivatedSpecified");
            }
        }
        
        /// <remarks/>
        public string portNum {
            get {
                return this.portNumField;
            }
            set {
                this.portNumField = value;
                this.RaisePropertyChanged("portNum");
            }
        }
        
        /// <remarks/>
        public string smNum {
            get {
                return this.smNumField;
            }
            set {
                this.smNumField = value;
                this.RaisePropertyChanged("smNum");
            }
        }
        
        /// <remarks/>
        public string devPortNum {
            get {
                return this.devPortNumField;
            }
            set {
                this.devPortNumField = value;
                this.RaisePropertyChanged("devPortNum");
            }
        }
        
        /// <remarks/>
        public long hlcode {
            get {
                return this.hlcodeField;
            }
            set {
                this.hlcodeField = value;
                this.RaisePropertyChanged("hlcode");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool hlcodeSpecified {
            get {
                return this.hlcodeFieldSpecified;
            }
            set {
                this.hlcodeFieldSpecified = value;
                this.RaisePropertyChanged("hlcodeSpecified");
            }
        }
        
        /// <remarks/>
        public long coId {
            get {
                return this.coIdField;
            }
            set {
                this.coIdField = value;
                this.RaisePropertyChanged("coId");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool coIdSpecified {
            get {
                return this.coIdFieldSpecified;
            }
            set {
                this.coIdFieldSpecified = value;
                this.RaisePropertyChanged("coIdSpecified");
            }
        }
        
        /// <remarks/>
        public string coIdPub {
            get {
                return this.coIdPubField;
            }
            set {
                this.coIdPubField = value;
                this.RaisePropertyChanged("coIdPub");
            }
        }
        
        /// <remarks/>
        public long mainCoId {
            get {
                return this.mainCoIdField;
            }
            set {
                this.mainCoIdField = value;
                this.RaisePropertyChanged("mainCoId");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool mainCoIdSpecified {
            get {
                return this.mainCoIdFieldSpecified;
            }
            set {
                this.mainCoIdFieldSpecified = value;
                this.RaisePropertyChanged("mainCoIdSpecified");
            }
        }
        
        /// <remarks/>
        public string mainCoIdPub {
            get {
                return this.mainCoIdPubField;
            }
            set {
                this.mainCoIdPubField = value;
                this.RaisePropertyChanged("mainCoIdPub");
            }
        }
        
        /// <remarks/>
        public long csId {
            get {
                return this.csIdField;
            }
            set {
                this.csIdField = value;
                this.RaisePropertyChanged("csId");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool csIdSpecified {
            get {
                return this.csIdFieldSpecified;
            }
            set {
                this.csIdFieldSpecified = value;
                this.RaisePropertyChanged("csIdSpecified");
            }
        }
        
        /// <remarks/>
        public string csIdPub {
            get {
                return this.csIdPubField;
            }
            set {
                this.csIdPubField = value;
                this.RaisePropertyChanged("csIdPub");
            }
        }
        
        /// <remarks/>
        public string description {
            get {
                return this.descriptionField;
            }
            set {
                this.descriptionField = value;
                this.RaisePropertyChanged("description");
            }
        }
        
        /// <remarks/>
        public bool currentDn {
            get {
                return this.currentDnField;
            }
            set {
                this.currentDnField = value;
                this.RaisePropertyChanged("currentDn");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool currentDnSpecified {
            get {
                return this.currentDnFieldSpecified;
            }
            set {
                this.currentDnFieldSpecified = value;
                this.RaisePropertyChanged("currentDnSpecified");
            }
        }
        
        /// <remarks/>
        public bool dnPending {
            get {
                return this.dnPendingField;
            }
            set {
                this.dnPendingField = value;
                this.RaisePropertyChanged("dnPending");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool dnPendingSpecified {
            get {
                return this.dnPendingFieldSpecified;
            }
            set {
                this.dnPendingFieldSpecified = value;
                this.RaisePropertyChanged("dnPendingSpecified");
            }
        }
        
        /// <remarks/>
        public bool markedForRerating {
            get {
                return this.markedForReratingField;
            }
            set {
                this.markedForReratingField = value;
                this.RaisePropertyChanged("markedForRerating");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool markedForReratingSpecified {
            get {
                return this.markedForReratingFieldSpecified;
            }
            set {
                this.markedForReratingFieldSpecified = value;
                this.RaisePropertyChanged("markedForReratingSpecified");
            }
        }
        
        /// <remarks/>
        public long csDealerid {
            get {
                return this.csDealeridField;
            }
            set {
                this.csDealeridField = value;
                this.RaisePropertyChanged("csDealerid");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool csDealeridSpecified {
            get {
                return this.csDealeridFieldSpecified;
            }
            set {
                this.csDealeridFieldSpecified = value;
                this.RaisePropertyChanged("csDealeridSpecified");
            }
        }
        
        /// <remarks/>
        public string paymentResp {
            get {
                return this.paymentRespField;
            }
            set {
                this.paymentRespField = value;
                this.RaisePropertyChanged("paymentResp");
            }
        }
        
        /// <remarks/>
        public string csContrResp {
            get {
                return this.csContrRespField;
            }
            set {
                this.csContrRespField = value;
                this.RaisePropertyChanged("csContrResp");
            }
        }
        
        /// <remarks/>
        public string paymentMethodInd {
            get {
                return this.paymentMethodIndField;
            }
            set {
                this.paymentMethodIndField = value;
                this.RaisePropertyChanged("paymentMethodInd");
            }
        }
        
        /// <remarks/>
        public long coTemplateId {
            get {
                return this.coTemplateIdField;
            }
            set {
                this.coTemplateIdField = value;
                this.RaisePropertyChanged("coTemplateId");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool coTemplateIdSpecified {
            get {
                return this.coTemplateIdFieldSpecified;
            }
            set {
                this.coTemplateIdFieldSpecified = value;
                this.RaisePropertyChanged("coTemplateIdSpecified");
            }
        }
        
        /// <remarks/>
        public string coTemplateIdPub {
            get {
                return this.coTemplateIdPubField;
            }
            set {
                this.coTemplateIdPubField = value;
                this.RaisePropertyChanged("coTemplateIdPub");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlArrayItemAttribute("salesChannel", IsNullable=false)]
        public string[] salesChannels {
            get {
                return this.salesChannelsField;
            }
            set {
                this.salesChannelsField = value;
                this.RaisePropertyChanged("salesChannels");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.7.2612.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://ericsson.com/services/ws_CIL_6/contractssearch")]
    public partial class contractsSearchResponse : object, System.ComponentModel.INotifyPropertyChanged {
        
        private contractsListpartResponse[] contractsField;
        
        private bool searchIsCompleteField;
        
        private bool searchIsCompleteFieldSpecified;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlArrayItemAttribute("item", IsNullable=false)]
        public contractsListpartResponse[] contracts {
            get {
                return this.contractsField;
            }
            set {
                this.contractsField = value;
                this.RaisePropertyChanged("contracts");
            }
        }
        
        /// <remarks/>
        public bool searchIsComplete {
            get {
                return this.searchIsCompleteField;
            }
            set {
                this.searchIsCompleteField = value;
                this.RaisePropertyChanged("searchIsComplete");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool searchIsCompleteSpecified {
            get {
                return this.searchIsCompleteFieldSpecified;
            }
            set {
                this.searchIsCompleteFieldSpecified = value;
                this.RaisePropertyChanged("searchIsCompleteSpecified");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.7.2612.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://ericsson.com/services/ws_CIL_6/sessionchange")]
    public partial class valuesListpartRequest : object, System.ComponentModel.INotifyPropertyChanged {
        
        private string keyField;
        
        private string valueField;
        
        /// <remarks/>
        public string key {
            get {
                return this.keyField;
            }
            set {
                this.keyField = value;
                this.RaisePropertyChanged("key");
            }
        }
        
        /// <remarks/>
        public string value {
            get {
                return this.valueField;
            }
            set {
                this.valueField = value;
                this.RaisePropertyChanged("value");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.7.2612.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://ericsson.com/services/ws_CIL_6/sessionchange")]
    public partial class sessionChangeRequest : object, System.ComponentModel.INotifyPropertyChanged {
        
        private valuesListpartRequest[] valuesField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlArrayItemAttribute("item", IsNullable=false)]
        public valuesListpartRequest[] values {
            get {
                return this.valuesField;
            }
            set {
                this.valuesField = value;
                this.RaisePropertyChanged("values");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class contractsSearchRequest1 {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://ericsson.com/services/ws_CIL_6/contractssearch", Order=0)]
        public AmxSoapServicesActivities.ContractsSearchService.contractsSearchRequest contractsSearchRequest;
        
        public contractsSearchRequest1() {
        }
        
        public contractsSearchRequest1(AmxSoapServicesActivities.ContractsSearchService.contractsSearchRequest contractsSearchRequest) {
            this.contractsSearchRequest = contractsSearchRequest;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class contractsSearchResponse1 {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://ericsson.com/services/ws_CIL_6/contractssearch", Order=0)]
        public AmxSoapServicesActivities.ContractsSearchService.contractsSearchResponse contractsSearchResponse;
        
        public contractsSearchResponse1() {
        }
        
        public contractsSearchResponse1(AmxSoapServicesActivities.ContractsSearchService.contractsSearchResponse contractsSearchResponse) {
            this.contractsSearchResponse = contractsSearchResponse;
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface ContractsSearchServiceChannel : AmxSoapServicesActivities.ContractsSearchService.ContractsSearchService, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class ContractsSearchServiceClient : System.ServiceModel.ClientBase<AmxSoapServicesActivities.ContractsSearchService.ContractsSearchService>, AmxSoapServicesActivities.ContractsSearchService.ContractsSearchService {
        
        public ContractsSearchServiceClient() {
        }
        
        public ContractsSearchServiceClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public ContractsSearchServiceClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public ContractsSearchServiceClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public ContractsSearchServiceClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        AmxSoapServicesActivities.ContractsSearchService.contractsSearchResponse1 AmxSoapServicesActivities.ContractsSearchService.ContractsSearchService.contractsSearch(AmxSoapServicesActivities.ContractsSearchService.contractsSearchRequest1 request) {
            return base.Channel.contractsSearch(request);
        }
        
        public AmxSoapServicesActivities.ContractsSearchService.contractsSearchResponse contractsSearch(AmxSoapServicesActivities.ContractsSearchService.contractsSearchRequest contractsSearchRequest) {
            AmxSoapServicesActivities.ContractsSearchService.contractsSearchRequest1 inValue = new AmxSoapServicesActivities.ContractsSearchService.contractsSearchRequest1();
            inValue.contractsSearchRequest = contractsSearchRequest;
            AmxSoapServicesActivities.ContractsSearchService.contractsSearchResponse1 retVal = ((AmxSoapServicesActivities.ContractsSearchService.ContractsSearchService)(this)).contractsSearch(inValue);
            return retVal.contractsSearchResponse;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<AmxSoapServicesActivities.ContractsSearchService.contractsSearchResponse1> AmxSoapServicesActivities.ContractsSearchService.ContractsSearchService.contractsSearchAsync(AmxSoapServicesActivities.ContractsSearchService.contractsSearchRequest1 request) {
            return base.Channel.contractsSearchAsync(request);
        }
        
        public System.Threading.Tasks.Task<AmxSoapServicesActivities.ContractsSearchService.contractsSearchResponse1> contractsSearchAsync(AmxSoapServicesActivities.ContractsSearchService.contractsSearchRequest contractsSearchRequest) {
            AmxSoapServicesActivities.ContractsSearchService.contractsSearchRequest1 inValue = new AmxSoapServicesActivities.ContractsSearchService.contractsSearchRequest1();
            inValue.contractsSearchRequest = contractsSearchRequest;
            return ((AmxSoapServicesActivities.ContractsSearchService.ContractsSearchService)(this)).contractsSearchAsync(inValue);
        }
    }
}
